/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ErrorResponse,
  ListPlacesParams,
  PlaceDetailDto,
  PlaceListResponse,
  PlaceRequest,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get all places for a team
 * @summary List places
 */
export const listPlaces = (
  slug: string,
  params?: ListPlacesParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<PlaceListResponse>(
    { url: `/api/teams/${slug}/places`, method: 'GET', params, signal },
    options
  )
}

export const getListPlacesQueryKey = (slug?: string, params?: ListPlacesParams) => {
  return [`/api/teams/${slug}/places`, ...(params ? [params] : [])] as const
}

export const getListPlacesQueryOptions = <
  TData = Awaited<ReturnType<typeof listPlaces>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  params?: ListPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListPlacesQueryKey(slug, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listPlaces>>> = ({ signal }) =>
    listPlaces(slug, params, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!slug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listPlaces>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPlacesQueryResult = NonNullable<Awaited<ReturnType<typeof listPlaces>>>
export type ListPlacesQueryError = ErrorType<void | ErrorResponse>

export function useListPlaces<
  TData = Awaited<ReturnType<typeof listPlaces>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  params: undefined | ListPlacesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlaces>>,
          TError,
          Awaited<ReturnType<typeof listPlaces>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPlaces<
  TData = Awaited<ReturnType<typeof listPlaces>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  params?: ListPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPlaces>>,
          TError,
          Awaited<ReturnType<typeof listPlaces>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPlaces<
  TData = Awaited<ReturnType<typeof listPlaces>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  params?: ListPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List places
 */

export function useListPlaces<
  TData = Awaited<ReturnType<typeof listPlaces>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  params?: ListPlacesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listPlaces>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListPlacesQueryOptions(slug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Create a new place for the team
 * @summary Create place
 */
export const createPlace = (
  slug: string,
  placeRequest: BodyType<PlaceRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<PlaceDetailDto>(
    {
      url: `/api/teams/${slug}/places`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: placeRequest,
      signal,
    },
    options
  )
}

export const getCreatePlaceMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPlace>>,
    TError,
    { slug: string; data: BodyType<PlaceRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPlace>>,
  TError,
  { slug: string; data: BodyType<PlaceRequest> },
  TContext
> => {
  const mutationKey = ['createPlace']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPlace>>,
    { slug: string; data: BodyType<PlaceRequest> }
  > = (props) => {
    const { slug, data } = props ?? {}

    return createPlace(slug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreatePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof createPlace>>>
export type CreatePlaceMutationBody = BodyType<PlaceRequest>
export type CreatePlaceMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create place
 */
export const useCreatePlace = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createPlace>>,
      TError,
      { slug: string; data: BodyType<PlaceRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createPlace>>,
  TError,
  { slug: string; data: BodyType<PlaceRequest> },
  TContext
> => {
  const mutationOptions = getCreatePlaceMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Update an existing place
 * @summary Update place
 */
export const updatePlace = (
  slug: string,
  placeId: string,
  placeRequest: BodyType<PlaceRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<PlaceDetailDto>(
    {
      url: `/api/teams/${slug}/places/${placeId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: placeRequest,
    },
    options
  )
}

export const getUpdatePlaceMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePlace>>,
    TError,
    { slug: string; placeId: string; data: BodyType<PlaceRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePlace>>,
  TError,
  { slug: string; placeId: string; data: BodyType<PlaceRequest> },
  TContext
> => {
  const mutationKey = ['updatePlace']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePlace>>,
    { slug: string; placeId: string; data: BodyType<PlaceRequest> }
  > = (props) => {
    const { slug, placeId, data } = props ?? {}

    return updatePlace(slug, placeId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdatePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof updatePlace>>>
export type UpdatePlaceMutationBody = BodyType<PlaceRequest>
export type UpdatePlaceMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update place
 */
export const useUpdatePlace = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePlace>>,
      TError,
      { slug: string; placeId: string; data: BodyType<PlaceRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updatePlace>>,
  TError,
  { slug: string; placeId: string; data: BodyType<PlaceRequest> },
  TContext
> => {
  const mutationOptions = getUpdatePlaceMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get a specific place by ID
 * @summary Get place details
 */
export const getPlace = (
  slug: string,
  placeId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<PlaceDetailDto>(
    { url: `/api/teams/${slug}/places/${placeId}`, method: 'GET', signal },
    options
  )
}

export const getGetPlaceQueryKey = (slug?: string, placeId?: string) => {
  return [`/api/teams/${slug}/places/${placeId}`] as const
}

export const getGetPlaceQueryOptions = <
  TData = Awaited<ReturnType<typeof getPlace>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  placeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetPlaceQueryKey(slug, placeId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPlace>>> = ({ signal }) =>
    getPlace(slug, placeId, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(slug && placeId), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPlace>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPlaceQueryResult = NonNullable<Awaited<ReturnType<typeof getPlace>>>
export type GetPlaceQueryError = ErrorType<void | ErrorResponse>

export function useGetPlace<
  TData = Awaited<ReturnType<typeof getPlace>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  placeId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace>>,
          TError,
          Awaited<ReturnType<typeof getPlace>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlace<
  TData = Awaited<ReturnType<typeof getPlace>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  placeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPlace>>,
          TError,
          Awaited<ReturnType<typeof getPlace>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPlace<
  TData = Awaited<ReturnType<typeof getPlace>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  placeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get place details
 */

export function useGetPlace<
  TData = Awaited<ReturnType<typeof getPlace>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  slug: string,
  placeId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPlace>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPlaceQueryOptions(slug, placeId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Soft delete a place
 * @summary Delete place
 */
export const deletePlace = (
  slug: string,
  placeId: string,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<void>(
    { url: `/api/teams/${slug}/places/${placeId}`, method: 'DELETE' },
    options
  )
}

export const getDeletePlaceMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePlace>>,
    TError,
    { slug: string; placeId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePlace>>,
  TError,
  { slug: string; placeId: string },
  TContext
> => {
  const mutationKey = ['deletePlace']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePlace>>,
    { slug: string; placeId: string }
  > = (props) => {
    const { slug, placeId } = props ?? {}

    return deletePlace(slug, placeId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeletePlaceMutationResult = NonNullable<Awaited<ReturnType<typeof deletePlace>>>

export type DeletePlaceMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete place
 */
export const useDeletePlace = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePlace>>,
      TError,
      { slug: string; placeId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deletePlace>>,
  TError,
  { slug: string; placeId: string },
  TContext
> => {
  const mutationOptions = getDeletePlaceMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
