/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ErrorResponse,
  ListRidesParams,
  RideDto,
  RideListResponse,
  RideParticipationDto,
  RideRequest,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get paginated list of rides for a team with optional filtering
 * @summary List rides
 */
export const listRides = (
  slug: string,
  params?: ListRidesParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideListResponse>(
    { url: `/api/teams/${slug}/rides`, method: 'GET', params, signal },
    options
  )
}

export const getListRidesQueryKey = (slug?: string, params?: ListRidesParams) => {
  return [`/api/teams/${slug}/rides`, ...(params ? [params] : [])] as const
}

export const getListRidesQueryOptions = <
  TData = Awaited<ReturnType<typeof listRides>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRidesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRides>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListRidesQueryKey(slug, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRides>>> = ({ signal }) =>
    listRides(slug, params, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!slug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listRides>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRidesQueryResult = NonNullable<Awaited<ReturnType<typeof listRides>>>
export type ListRidesQueryError = ErrorType<ErrorResponse>

export function useListRides<
  TData = Awaited<ReturnType<typeof listRides>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params: undefined | ListRidesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRides>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRides>>,
          TError,
          Awaited<ReturnType<typeof listRides>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRides<
  TData = Awaited<ReturnType<typeof listRides>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRidesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRides>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRides>>,
          TError,
          Awaited<ReturnType<typeof listRides>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRides<
  TData = Awaited<ReturnType<typeof listRides>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRidesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRides>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List rides
 */

export function useListRides<
  TData = Awaited<ReturnType<typeof listRides>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRidesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRides>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListRidesQueryOptions(slug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Create a new ride with optional groups
 * @summary Create ride
 */
export const createRide = (
  slug: string,
  rideRequest: BodyType<RideRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideDto>(
    {
      url: `/api/teams/${slug}/rides`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: rideRequest,
      signal,
    },
    options
  )
}

export const getCreateRideMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRide>>,
    TError,
    { slug: string; data: BodyType<RideRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRide>>,
  TError,
  { slug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationKey = ['createRide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRide>>,
    { slug: string; data: BodyType<RideRequest> }
  > = (props) => {
    const { slug, data } = props ?? {}

    return createRide(slug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateRideMutationResult = NonNullable<Awaited<ReturnType<typeof createRide>>>
export type CreateRideMutationBody = BodyType<RideRequest>
export type CreateRideMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create ride
 */
export const useCreateRide = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRide>>,
      TError,
      { slug: string; data: BodyType<RideRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createRide>>,
  TError,
  { slug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationOptions = getCreateRideMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Update ride information. Requires organizer permissions.
 * @summary Update ride
 */
export const updateRide = (
  slug: string,
  rideSlug: string,
  rideRequest: BodyType<RideRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<RideDto>(
    {
      url: `/api/teams/${slug}/rides/${rideSlug}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: rideRequest,
    },
    options
  )
}

export const getUpdateRideMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRide>>,
    TError,
    { slug: string; rideSlug: string; data: BodyType<RideRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRide>>,
  TError,
  { slug: string; rideSlug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationKey = ['updateRide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRide>>,
    { slug: string; rideSlug: string; data: BodyType<RideRequest> }
  > = (props) => {
    const { slug, rideSlug, data } = props ?? {}

    return updateRide(slug, rideSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateRideMutationResult = NonNullable<Awaited<ReturnType<typeof updateRide>>>
export type UpdateRideMutationBody = BodyType<RideRequest>
export type UpdateRideMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update ride
 */
export const useUpdateRide = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRide>>,
      TError,
      { slug: string; rideSlug: string; data: BodyType<RideRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateRide>>,
  TError,
  { slug: string; rideSlug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationOptions = getUpdateRideMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get detailed ride information including groups
 * @summary Get ride details
 */
export const getRide = (
  slug: string,
  rideSlug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideDto>(
    { url: `/api/teams/${slug}/rides/${rideSlug}`, method: 'GET', signal },
    options
  )
}

export const getGetRideQueryKey = (slug?: string, rideSlug?: string) => {
  return [`/api/teams/${slug}/rides/${rideSlug}`] as const
}

export const getGetRideQueryOptions = <
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRideQueryKey(slug, rideSlug)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRide>>> = ({ signal }) =>
    getRide(slug, rideSlug, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(slug && rideSlug), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRide>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRideQueryResult = NonNullable<Awaited<ReturnType<typeof getRide>>>
export type GetRideQueryError = ErrorType<ErrorResponse>

export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  rideSlug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRide>>,
          TError,
          Awaited<ReturnType<typeof getRide>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRide>>,
          TError,
          Awaited<ReturnType<typeof getRide>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ride details
 */

export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRideQueryOptions(slug, rideSlug, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Soft delete a ride. Requires organizer permissions.
 * @summary Delete ride
 */
export const deleteRide = (
  slug: string,
  rideSlug: string,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<void>(
    { url: `/api/teams/${slug}/rides/${rideSlug}`, method: 'DELETE' },
    options
  )
}

export const getDeleteRideMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRide>>,
    TError,
    { slug: string; rideSlug: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRide>>,
  TError,
  { slug: string; rideSlug: string },
  TContext
> => {
  const mutationKey = ['deleteRide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRide>>,
    { slug: string; rideSlug: string }
  > = (props) => {
    const { slug, rideSlug } = props ?? {}

    return deleteRide(slug, rideSlug, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteRideMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRide>>>

export type DeleteRideMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete ride
 */
export const useDeleteRide = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRide>>,
      TError,
      { slug: string; rideSlug: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRide>>,
  TError,
  { slug: string; rideSlug: string },
  TContext
> => {
  const mutationOptions = getDeleteRideMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Join a ride group
 * @summary Join ride group
 */
export const joinGroup = (
  slug: string,
  rideSlug: string,
  groupId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideParticipationDto>(
    { url: `/api/teams/${slug}/rides/${rideSlug}/groups/${groupId}/join`, method: 'POST', signal },
    options
  )
}

export const getJoinGroupMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinGroup>>,
    TError,
    { slug: string; rideSlug: string; groupId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof joinGroup>>,
  TError,
  { slug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationKey = ['joinGroup']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof joinGroup>>,
    { slug: string; rideSlug: string; groupId: string }
  > = (props) => {
    const { slug, rideSlug, groupId } = props ?? {}

    return joinGroup(slug, rideSlug, groupId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type JoinGroupMutationResult = NonNullable<Awaited<ReturnType<typeof joinGroup>>>

export type JoinGroupMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Join ride group
 */
export const useJoinGroup = <TError = ErrorType<ErrorResponse | void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof joinGroup>>,
      TError,
      { slug: string; rideSlug: string; groupId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof joinGroup>>,
  TError,
  { slug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationOptions = getJoinGroupMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Leave a ride group
 * @summary Leave ride group
 */
export const leaveGroup = (
  slug: string,
  rideSlug: string,
  groupId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<void>(
    { url: `/api/teams/${slug}/rides/${rideSlug}/groups/${groupId}/leave`, method: 'POST', signal },
    options
  )
}

export const getLeaveGroupMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveGroup>>,
    TError,
    { slug: string; rideSlug: string; groupId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof leaveGroup>>,
  TError,
  { slug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationKey = ['leaveGroup']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leaveGroup>>,
    { slug: string; rideSlug: string; groupId: string }
  > = (props) => {
    const { slug, rideSlug, groupId } = props ?? {}

    return leaveGroup(slug, rideSlug, groupId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LeaveGroupMutationResult = NonNullable<Awaited<ReturnType<typeof leaveGroup>>>

export type LeaveGroupMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Leave ride group
 */
export const useLeaveGroup = <TError = ErrorType<ErrorResponse | void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leaveGroup>>,
      TError,
      { slug: string; rideSlug: string; groupId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leaveGroup>>,
  TError,
  { slug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationOptions = getLeaveGroupMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
