/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  ErrorResponse,
  RideDto,
  RideParticipationDto,
  RideRequest,
  SlugChangeRequest,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Create a new ride with optional groups
 * @summary Create ride
 */
export const createRide = (
  teamSlug: string,
  rideRequest: BodyType<RideRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideDto>(
    {
      url: `/api/teams/${teamSlug}/rides`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: rideRequest,
      signal,
    },
    options
  )
}

export const getCreateRideMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRide>>,
    TError,
    { teamSlug: string; data: BodyType<RideRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRide>>,
  TError,
  { teamSlug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationKey = ['createRide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRide>>,
    { teamSlug: string; data: BodyType<RideRequest> }
  > = (props) => {
    const { teamSlug, data } = props ?? {}

    return createRide(teamSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateRideMutationResult = NonNullable<Awaited<ReturnType<typeof createRide>>>
export type CreateRideMutationBody = BodyType<RideRequest>
export type CreateRideMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create ride
 */
export const useCreateRide = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRide>>,
      TError,
      { teamSlug: string; data: BodyType<RideRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createRide>>,
  TError,
  { teamSlug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationOptions = getCreateRideMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Update ride information. Requires organizer permissions.
 * @summary Update ride
 */
export const updateRide = (
  teamSlug: string,
  rideSlug: string,
  rideRequest: BodyType<RideRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<RideDto>(
    {
      url: `/api/teams/${teamSlug}/rides/${rideSlug}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: rideRequest,
    },
    options
  )
}

export const getUpdateRideMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRide>>,
    TError,
    { teamSlug: string; rideSlug: string; data: BodyType<RideRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRide>>,
  TError,
  { teamSlug: string; rideSlug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationKey = ['updateRide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRide>>,
    { teamSlug: string; rideSlug: string; data: BodyType<RideRequest> }
  > = (props) => {
    const { teamSlug, rideSlug, data } = props ?? {}

    return updateRide(teamSlug, rideSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateRideMutationResult = NonNullable<Awaited<ReturnType<typeof updateRide>>>
export type UpdateRideMutationBody = BodyType<RideRequest>
export type UpdateRideMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update ride
 */
export const useUpdateRide = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRide>>,
      TError,
      { teamSlug: string; rideSlug: string; data: BodyType<RideRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateRide>>,
  TError,
  { teamSlug: string; rideSlug: string; data: BodyType<RideRequest> },
  TContext
> => {
  const mutationOptions = getUpdateRideMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get detailed ride information including groups
 * @summary Get ride details
 */
export const getRide = (
  teamSlug: string,
  rideSlug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideDto>(
    { url: `/api/teams/${teamSlug}/rides/${rideSlug}`, method: 'GET', signal },
    options
  )
}

export const getGetRideQueryKey = (teamSlug?: string, rideSlug?: string) => {
  return [`/api/teams/${teamSlug}/rides/${rideSlug}`] as const
}

export const getGetRideQueryOptions = <
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRideQueryKey(teamSlug, rideSlug)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRide>>> = ({ signal }) =>
    getRide(teamSlug, rideSlug, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(teamSlug && rideSlug),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type GetRideQueryResult = NonNullable<Awaited<ReturnType<typeof getRide>>>
export type GetRideQueryError = ErrorType<ErrorResponse>

export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  rideSlug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRide>>,
          TError,
          Awaited<ReturnType<typeof getRide>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRide>>,
          TError,
          Awaited<ReturnType<typeof getRide>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ride details
 */

export function useGetRide<
  TData = Awaited<ReturnType<typeof getRide>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  rideSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRide>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRideQueryOptions(teamSlug, rideSlug, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Soft delete a ride. Requires organizer permissions.
 * @summary Delete ride
 */
export const deleteRide = (
  teamSlug: string,
  rideSlug: string,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<void>(
    { url: `/api/teams/${teamSlug}/rides/${rideSlug}`, method: 'DELETE' },
    options
  )
}

export const getDeleteRideMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRide>>,
    TError,
    { teamSlug: string; rideSlug: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRide>>,
  TError,
  { teamSlug: string; rideSlug: string },
  TContext
> => {
  const mutationKey = ['deleteRide']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRide>>,
    { teamSlug: string; rideSlug: string }
  > = (props) => {
    const { teamSlug, rideSlug } = props ?? {}

    return deleteRide(teamSlug, rideSlug, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteRideMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRide>>>

export type DeleteRideMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete ride
 */
export const useDeleteRide = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRide>>,
      TError,
      { teamSlug: string; rideSlug: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRide>>,
  TError,
  { teamSlug: string; rideSlug: string },
  TContext
> => {
  const mutationOptions = getDeleteRideMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Join a ride group
 * @summary Join ride group
 */
export const joinGroup = (
  teamSlug: string,
  rideSlug: string,
  groupId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RideParticipationDto>(
    {
      url: `/api/teams/${teamSlug}/rides/${rideSlug}/groups/${groupId}/join`,
      method: 'POST',
      signal,
    },
    options
  )
}

export const getJoinGroupMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof joinGroup>>,
    TError,
    { teamSlug: string; rideSlug: string; groupId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof joinGroup>>,
  TError,
  { teamSlug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationKey = ['joinGroup']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof joinGroup>>,
    { teamSlug: string; rideSlug: string; groupId: string }
  > = (props) => {
    const { teamSlug, rideSlug, groupId } = props ?? {}

    return joinGroup(teamSlug, rideSlug, groupId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type JoinGroupMutationResult = NonNullable<Awaited<ReturnType<typeof joinGroup>>>

export type JoinGroupMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Join ride group
 */
export const useJoinGroup = <TError = ErrorType<ErrorResponse | void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof joinGroup>>,
      TError,
      { teamSlug: string; rideSlug: string; groupId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof joinGroup>>,
  TError,
  { teamSlug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationOptions = getJoinGroupMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Leave a ride group
 * @summary Leave ride group
 */
export const leaveGroup = (
  teamSlug: string,
  rideSlug: string,
  groupId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<void>(
    {
      url: `/api/teams/${teamSlug}/rides/${rideSlug}/groups/${groupId}/leave`,
      method: 'POST',
      signal,
    },
    options
  )
}

export const getLeaveGroupMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof leaveGroup>>,
    TError,
    { teamSlug: string; rideSlug: string; groupId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof leaveGroup>>,
  TError,
  { teamSlug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationKey = ['leaveGroup']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof leaveGroup>>,
    { teamSlug: string; rideSlug: string; groupId: string }
  > = (props) => {
    const { teamSlug, rideSlug, groupId } = props ?? {}

    return leaveGroup(teamSlug, rideSlug, groupId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type LeaveGroupMutationResult = NonNullable<Awaited<ReturnType<typeof leaveGroup>>>

export type LeaveGroupMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Leave ride group
 */
export const useLeaveGroup = <TError = ErrorType<ErrorResponse | void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof leaveGroup>>,
      TError,
      { teamSlug: string; rideSlug: string; groupId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof leaveGroup>>,
  TError,
  { teamSlug: string; rideSlug: string; groupId: string },
  TContext
> => {
  const mutationOptions = getLeaveGroupMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Change ride URL slug. Requires organizer permissions.
 * @summary Change ride slug
 */
export const changeRideSlug = (
  teamSlug: string,
  rideSlug: string,
  slugChangeRequest: BodyType<SlugChangeRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<RideDto>(
    {
      url: `/api/teams/${teamSlug}/rides/${rideSlug}/slug`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: slugChangeRequest,
    },
    options
  )
}

export const getChangeRideSlugMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeRideSlug>>,
    TError,
    { teamSlug: string; rideSlug: string; data: BodyType<SlugChangeRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeRideSlug>>,
  TError,
  { teamSlug: string; rideSlug: string; data: BodyType<SlugChangeRequest> },
  TContext
> => {
  const mutationKey = ['changeRideSlug']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeRideSlug>>,
    { teamSlug: string; rideSlug: string; data: BodyType<SlugChangeRequest> }
  > = (props) => {
    const { teamSlug, rideSlug, data } = props ?? {}

    return changeRideSlug(teamSlug, rideSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChangeRideSlugMutationResult = NonNullable<Awaited<ReturnType<typeof changeRideSlug>>>
export type ChangeRideSlugMutationBody = BodyType<SlugChangeRequest>
export type ChangeRideSlugMutationError = ErrorType<ErrorResponse>

/**
 * @summary Change ride slug
 */
export const useChangeRideSlug = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeRideSlug>>,
      TError,
      { teamSlug: string; rideSlug: string; data: BodyType<SlugChangeRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof changeRideSlug>>,
  TError,
  { teamSlug: string; rideSlug: string; data: BodyType<SlugChangeRequest> },
  TContext
> => {
  const mutationOptions = getChangeRideSlugMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
