/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AdDto,
  AdEditDto,
  AdListResponse,
  AdRequest,
  ErrorResponse,
  ListAdsParams,
  SlugChangeRequest,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get paginated list of ads for a team with optional filtering
 * @summary List ads
 */
export const listAds = (
  teamSlug: string,
  params?: ListAdsParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdListResponse>(
    { url: `/api/teams/${teamSlug}/ads`, method: 'GET', params, signal },
    options
  )
}

export const getListAdsQueryKey = (teamSlug: string, params?: ListAdsParams) => {
  return [`/api/teams/${teamSlug}/ads`, ...(params ? [params] : [])] as const
}

export const getListAdsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  params?: ListAdsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListAdsQueryKey(teamSlug, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAds>>> = ({ signal }) =>
    listAds(teamSlug, params, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!teamSlug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAdsQueryResult = NonNullable<Awaited<ReturnType<typeof listAds>>>
export type ListAdsQueryError = ErrorType<void | ErrorResponse>

export function useListAds<
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  params: undefined | ListAdsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAds>>,
          TError,
          Awaited<ReturnType<typeof listAds>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAds<
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  params?: ListAdsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAds>>,
          TError,
          Awaited<ReturnType<typeof listAds>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAds<
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  params?: ListAdsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List ads
 */

export function useListAds<
  TData = Awaited<ReturnType<typeof listAds>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  params?: ListAdsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAds>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListAdsQueryOptions(teamSlug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Create a new ad. Any team member can create ads.
 * @summary Create ad
 */
export const createAd = (
  teamSlug: string,
  adRequest: BodyType<AdRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdDto>(
    {
      url: `/api/teams/${teamSlug}/ads`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: adRequest,
      signal,
    },
    options
  )
}

export const getCreateAdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAd>>,
    TError,
    { teamSlug: string; data: BodyType<AdRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAd>>,
  TError,
  { teamSlug: string; data: BodyType<AdRequest> },
  TContext
> => {
  const mutationKey = ['createAd']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAd>>,
    { teamSlug: string; data: BodyType<AdRequest> }
  > = (props) => {
    const { teamSlug, data } = props ?? {}

    return createAd(teamSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateAdMutationResult = NonNullable<Awaited<ReturnType<typeof createAd>>>
export type CreateAdMutationBody = BodyType<AdRequest>
export type CreateAdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create ad
 */
export const useCreateAd = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAd>>,
      TError,
      { teamSlug: string; data: BodyType<AdRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createAd>>,
  TError,
  { teamSlug: string; data: BodyType<AdRequest> },
  TContext
> => {
  return useMutation(getCreateAdMutationOptions(options), queryClient)
}
/**
 * Update ad information. Only the creator or an admin can update.
 * @summary Update ad
 */
export const updateAd = (
  teamSlug: string,
  slug: string,
  adRequest: BodyType<AdRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdDto>(
    {
      url: `/api/teams/${teamSlug}/ads/${slug}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: adRequest,
      signal,
    },
    options
  )
}

export const getUpdateAdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAd>>,
    TError,
    { teamSlug: string; slug: string; data: BodyType<AdRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAd>>,
  TError,
  { teamSlug: string; slug: string; data: BodyType<AdRequest> },
  TContext
> => {
  const mutationKey = ['updateAd']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAd>>,
    { teamSlug: string; slug: string; data: BodyType<AdRequest> }
  > = (props) => {
    const { teamSlug, slug, data } = props ?? {}

    return updateAd(teamSlug, slug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateAdMutationResult = NonNullable<Awaited<ReturnType<typeof updateAd>>>
export type UpdateAdMutationBody = BodyType<AdRequest>
export type UpdateAdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update ad
 */
export const useUpdateAd = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateAd>>,
      TError,
      { teamSlug: string; slug: string; data: BodyType<AdRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateAd>>,
  TError,
  { teamSlug: string; slug: string; data: BodyType<AdRequest> },
  TContext
> => {
  return useMutation(getUpdateAdMutationOptions(options), queryClient)
}
/**
 * Get detailed ad information
 * @summary Get ad details
 */
export const getAd = (
  teamSlug: string,
  slug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdDto>(
    { url: `/api/teams/${teamSlug}/ads/${slug}`, method: 'GET', signal },
    options
  )
}

export const getGetAdQueryKey = (teamSlug: string, slug: string) => {
  return [`/api/teams/${teamSlug}/ads/${slug}`] as const
}

export const getGetAdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAd>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAd>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAdQueryKey(teamSlug, slug)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAd>>> = ({ signal }) =>
    getAd(teamSlug, slug, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(teamSlug && slug), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAd>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdQueryResult = NonNullable<Awaited<ReturnType<typeof getAd>>>
export type GetAdQueryError = ErrorType<void | ErrorResponse>

export function useGetAd<
  TData = Awaited<ReturnType<typeof getAd>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAd>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAd>>,
          TError,
          Awaited<ReturnType<typeof getAd>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAd<
  TData = Awaited<ReturnType<typeof getAd>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAd>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAd>>,
          TError,
          Awaited<ReturnType<typeof getAd>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAd<
  TData = Awaited<ReturnType<typeof getAd>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAd>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ad details
 */

export function useGetAd<
  TData = Awaited<ReturnType<typeof getAd>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAd>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAdQueryOptions(teamSlug, slug, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Soft delete an ad. Only the creator or an admin can delete.
 * @summary Delete ad
 */
export const deleteAd = (
  teamSlug: string,
  slug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<void>(
    { url: `/api/teams/${teamSlug}/ads/${slug}`, method: 'DELETE', signal },
    options
  )
}

export const getDeleteAdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAd>>,
    TError,
    { teamSlug: string; slug: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAd>>,
  TError,
  { teamSlug: string; slug: string },
  TContext
> => {
  const mutationKey = ['deleteAd']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAd>>,
    { teamSlug: string; slug: string }
  > = (props) => {
    const { teamSlug, slug } = props ?? {}

    return deleteAd(teamSlug, slug, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteAdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAd>>>

export type DeleteAdMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete ad
 */
export const useDeleteAd = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAd>>,
      TError,
      { teamSlug: string; slug: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAd>>,
  TError,
  { teamSlug: string; slug: string },
  TContext
> => {
  return useMutation(getDeleteAdMutationOptions(options), queryClient)
}
/**
 * Get detailed ad information
 * @summary Get ad details for edit
 */
export const getAdEdit = (
  teamSlug: string,
  slug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdEditDto>(
    { url: `/api/teams/${teamSlug}/ads/${slug}/edit`, method: 'GET', signal },
    options
  )
}

export const getGetAdEditQueryKey = (teamSlug: string, slug: string) => {
  return [`/api/teams/${teamSlug}/ads/${slug}/edit`] as const
}

export const getGetAdEditQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdEdit>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdEdit>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAdEditQueryKey(teamSlug, slug)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdEdit>>> = ({ signal }) =>
    getAdEdit(teamSlug, slug, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(teamSlug && slug), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdEdit>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAdEditQueryResult = NonNullable<Awaited<ReturnType<typeof getAdEdit>>>
export type GetAdEditQueryError = ErrorType<void | ErrorResponse>

export function useGetAdEdit<
  TData = Awaited<ReturnType<typeof getAdEdit>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdEdit>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdEdit>>,
          TError,
          Awaited<ReturnType<typeof getAdEdit>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdEdit<
  TData = Awaited<ReturnType<typeof getAdEdit>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdEdit>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAdEdit>>,
          TError,
          Awaited<ReturnType<typeof getAdEdit>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAdEdit<
  TData = Awaited<ReturnType<typeof getAdEdit>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdEdit>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get ad details for edit
 */

export function useGetAdEdit<
  TData = Awaited<ReturnType<typeof getAdEdit>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  teamSlug: string,
  slug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAdEdit>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAdEditQueryOptions(teamSlug, slug, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  return { ...query, queryKey: queryOptions.queryKey }
}

/**
 * Change ad URL slug. Requires admin permissions.
 * @summary Change ad slug
 */
export const changeAdSlug = (
  teamSlug: string,
  slug: string,
  slugChangeRequest: BodyType<SlugChangeRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdDto>(
    {
      url: `/api/teams/${teamSlug}/ads/${slug}/slug`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: slugChangeRequest,
      signal,
    },
    options
  )
}

export const getChangeAdSlugMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeAdSlug>>,
    TError,
    { teamSlug: string; slug: string; data: BodyType<SlugChangeRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeAdSlug>>,
  TError,
  { teamSlug: string; slug: string; data: BodyType<SlugChangeRequest> },
  TContext
> => {
  const mutationKey = ['changeAdSlug']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeAdSlug>>,
    { teamSlug: string; slug: string; data: BodyType<SlugChangeRequest> }
  > = (props) => {
    const { teamSlug, slug, data } = props ?? {}

    return changeAdSlug(teamSlug, slug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChangeAdSlugMutationResult = NonNullable<Awaited<ReturnType<typeof changeAdSlug>>>
export type ChangeAdSlugMutationBody = BodyType<SlugChangeRequest>
export type ChangeAdSlugMutationError = ErrorType<ErrorResponse>

/**
 * @summary Change ad slug
 */
export const useChangeAdSlug = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeAdSlug>>,
      TError,
      { teamSlug: string; slug: string; data: BodyType<SlugChangeRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof changeAdSlug>>,
  TError,
  { teamSlug: string; slug: string; data: BodyType<SlugChangeRequest> },
  TContext
> => {
  return useMutation(getChangeAdSlugMutationOptions(options), queryClient)
}
