openapi_generator:
  schema_path: ../contracts/openapi.yaml
  output_directory: lib/api/generated
  json_serializer: freezed
  root_client: true
  root_client_name: TriblyApiClient
  client_postfix: Client
  unknown_enum_value: true
  put_clients_in_folder: true
  export_file: true
