/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get a paginated list of all users
 * @summary List all users
 */
export const listUsersQueryPageDefault = 0
export const listUsersQuerySizeDefault = 20

export const listUsersQueryParams = zod.object({
  adminOnly: zod.boolean().optional().describe('Show only platform admins'),
  domainId: zod.string().optional().describe('Filter by domain ID'),
  page: zod.number().optional().describe('Page number (0-indexed)'),
  search: zod.string().optional().describe('Search by email or name'),
  size: zod.number().default(listUsersQuerySizeDefault).describe('Page size'),
})

export const listUsersResponse = zod
  .object({
    users: zod
      .array(
        zod
          .object({
            id: zod.string().describe('User ID (TSID)'),
            email: zod.string().describe('User email address'),
            displayName: zod.string().describe('User display name'),
            domainId: zod.string().describe('Domain ID this user belongs to'),
            domainName: zod.string().describe('Domain hostname'),
            platformRole: zod.enum(['PLATFORM_ADMIN']).optional(),
            emailVerified: zod.boolean().describe('Whether email is verified'),
            createdAt: zod.iso.datetime({}),
            lastLoginAt: zod.iso.datetime({}).optional(),
          })
          .describe('Admin user view with domain info')
      )
      .describe('List of users'),
    total: zod.number().describe('Total number of users'),
    page: zod.number().describe('Current page number'),
    size: zod.number().describe('Page size'),
  })
  .describe('Paginated admin user list response')

/**
 * Get detailed user information
 * @summary Get user details
 */
export const getAdminUserParams = zod.object({
  userId: zod.string().describe('User ID'),
})

export const getAdminUserResponse = zod
  .object({
    id: zod.string().describe('User ID (TSID)'),
    email: zod.string().describe('User email address'),
    displayName: zod.string().describe('User display name'),
    domainId: zod.string().describe('Domain ID this user belongs to'),
    domainName: zod.string().describe('Domain hostname'),
    platformRole: zod.enum(['PLATFORM_ADMIN']).optional(),
    emailVerified: zod.boolean().describe('Whether email is verified'),
    createdAt: zod.iso.datetime({}),
    lastLoginAt: zod.iso.datetime({}).optional(),
  })
  .describe('Admin user view with domain info')

/**
 * Assign or remove a platform role from a user
 * @summary Assign platform role
 */
export const assignPlatformRoleParams = zod.object({
  userId: zod.string().describe('User ID'),
})

export const assignPlatformRoleBody = zod
  .object({
    role: zod.enum(['PLATFORM_ADMIN']).optional(),
  })
  .describe('Request to assign or remove platform role')

export const assignPlatformRoleResponse = zod
  .object({
    id: zod.string().describe('User ID (TSID)'),
    email: zod.string().describe('User email address'),
    displayName: zod.string().describe('User display name'),
    domainId: zod.string().describe('Domain ID this user belongs to'),
    domainName: zod.string().describe('Domain hostname'),
    platformRole: zod.enum(['PLATFORM_ADMIN']).optional(),
    emailVerified: zod.boolean().describe('Whether email is verified'),
    createdAt: zod.iso.datetime({}),
    lastLoginAt: zod.iso.datetime({}).optional(),
  })
  .describe('Admin user view with domain info')
