/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CreateRouteBody,
  ErrorResponse,
  ListAllRoutesParams,
  ListRoutesParams,
  RouteDetailDto,
  RouteDto,
  RouteListResponse,
  SlugChangeRequest,
  UpdateRouteBody,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get paginated list of routes from all accessible teams (user's teams + public teams)
 * @summary List all routes
 */
export const listAllRoutes = (
  params?: ListAllRoutesParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RouteListResponse>(
    { url: `/api/routes`, method: 'GET', params, signal },
    options
  )
}

export const getListAllRoutesQueryKey = (params?: ListAllRoutesParams) => {
  return [`/api/routes`, ...(params ? [params] : [])] as const
}

export const getListAllRoutesQueryOptions = <
  TData = Awaited<ReturnType<typeof listAllRoutes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAllRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListAllRoutesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAllRoutes>>> = ({ signal }) =>
    listAllRoutes(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAllRoutes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAllRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof listAllRoutes>>>
export type ListAllRoutesQueryError = ErrorType<unknown>

export function useListAllRoutes<
  TData = Awaited<ReturnType<typeof listAllRoutes>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | ListAllRoutesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllRoutes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllRoutes>>,
          TError,
          Awaited<ReturnType<typeof listAllRoutes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllRoutes<
  TData = Awaited<ReturnType<typeof listAllRoutes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAllRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllRoutes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAllRoutes>>,
          TError,
          Awaited<ReturnType<typeof listAllRoutes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAllRoutes<
  TData = Awaited<ReturnType<typeof listAllRoutes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAllRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all routes
 */

export function useListAllRoutes<
  TData = Awaited<ReturnType<typeof listAllRoutes>>,
  TError = ErrorType<unknown>,
>(
  params?: ListAllRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listAllRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListAllRoutesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Get paginated list of routes for a team with optional filters and sorting
 * @summary List routes
 */
export const listRoutes = (
  slug: string,
  params?: ListRoutesParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RouteListResponse>(
    { url: `/api/teams/${slug}/routes`, method: 'GET', params, signal },
    options
  )
}

export const getListRoutesQueryKey = (slug?: string, params?: ListRoutesParams) => {
  return [`/api/teams/${slug}/routes`, ...(params ? [params] : [])] as const
}

export const getListRoutesQueryOptions = <
  TData = Awaited<ReturnType<typeof listRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListRoutesQueryKey(slug, params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRoutes>>> = ({ signal }) =>
    listRoutes(slug, params, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!slug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listRoutes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof listRoutes>>>
export type ListRoutesQueryError = ErrorType<ErrorResponse>

export function useListRoutes<
  TData = Awaited<ReturnType<typeof listRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params: undefined | ListRoutesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRoutes>>,
          TError,
          Awaited<ReturnType<typeof listRoutes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRoutes<
  TData = Awaited<ReturnType<typeof listRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRoutes>>,
          TError,
          Awaited<ReturnType<typeof listRoutes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRoutes<
  TData = Awaited<ReturnType<typeof listRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List routes
 */

export function useListRoutes<
  TData = Awaited<ReturnType<typeof listRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  params?: ListRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListRoutesQueryOptions(slug, params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Create a new route by uploading a GPX file
 * @summary Create route
 */
export const createRoute = (
  slug: string,
  createRouteBody: BodyType<CreateRouteBody>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  const formData = new FormData()
  if (createRouteBody.route !== undefined) {
    formData.append(`route`, JSON.stringify(createRouteBody.route))
  }
  if (createRouteBody.gpxFile !== undefined) {
    formData.append(`gpxFile`, createRouteBody.gpxFile)
  }

  return axiosMutator<RouteDto>(
    {
      url: `/api/teams/${slug}/routes`,
      method: 'POST',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
      signal,
    },
    options
  )
}

export const getCreateRouteMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createRoute>>,
    TError,
    { slug: string; data: BodyType<CreateRouteBody> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createRoute>>,
  TError,
  { slug: string; data: BodyType<CreateRouteBody> },
  TContext
> => {
  const mutationKey = ['createRoute']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createRoute>>,
    { slug: string; data: BodyType<CreateRouteBody> }
  > = (props) => {
    const { slug, data } = props ?? {}

    return createRoute(slug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateRouteMutationResult = NonNullable<Awaited<ReturnType<typeof createRoute>>>
export type CreateRouteMutationBody = BodyType<CreateRouteBody>
export type CreateRouteMutationError = ErrorType<ErrorResponse>

/**
 * @summary Create route
 */
export const useCreateRoute = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createRoute>>,
      TError,
      { slug: string; data: BodyType<CreateRouteBody> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createRoute>>,
  TError,
  { slug: string; data: BodyType<CreateRouteBody> },
  TContext
> => {
  const mutationOptions = getCreateRouteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Update route metadata (name, markdown, etc.) and optionally replace the GPX file. If a new GPX file is provided, the old track data and climbs will be replaced.
 * @summary Update route
 */
export const updateRoute = (
  slug: string,
  routeSlug: string,
  updateRouteBody: BodyType<UpdateRouteBody>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  const formData = new FormData()
  if (updateRouteBody.route !== undefined) {
    formData.append(`route`, JSON.stringify(updateRouteBody.route))
  }
  if (updateRouteBody.gpxFile !== undefined) {
    formData.append(`gpxFile`, updateRouteBody.gpxFile)
  }

  return axiosMutator<RouteDto>(
    {
      url: `/api/teams/${slug}/routes/${routeSlug}`,
      method: 'PUT',
      headers: { 'Content-Type': 'multipart/form-data' },
      data: formData,
    },
    options
  )
}

export const getUpdateRouteMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateRoute>>,
    TError,
    { slug: string; routeSlug: string; data: BodyType<UpdateRouteBody> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateRoute>>,
  TError,
  { slug: string; routeSlug: string; data: BodyType<UpdateRouteBody> },
  TContext
> => {
  const mutationKey = ['updateRoute']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateRoute>>,
    { slug: string; routeSlug: string; data: BodyType<UpdateRouteBody> }
  > = (props) => {
    const { slug, routeSlug, data } = props ?? {}

    return updateRoute(slug, routeSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateRouteMutationResult = NonNullable<Awaited<ReturnType<typeof updateRoute>>>
export type UpdateRouteMutationBody = BodyType<UpdateRouteBody>
export type UpdateRouteMutationError = ErrorType<ErrorResponse>

/**
 * @summary Update route
 */
export const useUpdateRoute = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateRoute>>,
      TError,
      { slug: string; routeSlug: string; data: BodyType<UpdateRouteBody> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateRoute>>,
  TError,
  { slug: string; routeSlug: string; data: BodyType<UpdateRouteBody> },
  TContext
> => {
  const mutationOptions = getUpdateRouteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get detailed route information including GPS coordinates and statistics
 * @summary Get route details
 */
export const getRoute = (
  slug: string,
  routeSlug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<RouteDetailDto>(
    { url: `/api/teams/${slug}/routes/${routeSlug}`, method: 'GET', signal },
    options
  )
}

export const getGetRouteQueryKey = (slug?: string, routeSlug?: string) => {
  return [`/api/teams/${slug}/routes/${routeSlug}`] as const
}

export const getGetRouteQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRouteQueryKey(slug, routeSlug)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoute>>> = ({ signal }) =>
    getRoute(slug, routeSlug, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!(slug && routeSlug), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoute>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRouteQueryResult = NonNullable<Awaited<ReturnType<typeof getRoute>>>
export type GetRouteQueryError = ErrorType<ErrorResponse>

export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  routeSlug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoute>>,
          TError,
          Awaited<ReturnType<typeof getRoute>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoute>>,
          TError,
          Awaited<ReturnType<typeof getRoute>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get route details
 */

export function useGetRoute<
  TData = Awaited<ReturnType<typeof getRoute>>,
  TError = ErrorType<ErrorResponse>,
>(
  slug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoute>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRouteQueryOptions(slug, routeSlug, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Soft delete a route. Requires route creator or team admin permissions.
 * @summary Delete route
 */
export const deleteRoute = (
  slug: string,
  routeSlug: string,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<void>(
    { url: `/api/teams/${slug}/routes/${routeSlug}`, method: 'DELETE' },
    options
  )
}

export const getDeleteRouteMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRoute>>,
    TError,
    { slug: string; routeSlug: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRoute>>,
  TError,
  { slug: string; routeSlug: string },
  TContext
> => {
  const mutationKey = ['deleteRoute']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRoute>>,
    { slug: string; routeSlug: string }
  > = (props) => {
    const { slug, routeSlug } = props ?? {}

    return deleteRoute(slug, routeSlug, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteRouteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoute>>>

export type DeleteRouteMutationError = ErrorType<ErrorResponse>

/**
 * @summary Delete route
 */
export const useDeleteRoute = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRoute>>,
      TError,
      { slug: string; routeSlug: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRoute>>,
  TError,
  { slug: string; routeSlug: string },
  TContext
> => {
  const mutationOptions = getDeleteRouteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Change route URL slug. Requires organizer permissions.
 * @summary Change route slug
 */
export const changeRouteSlug = (
  slug: string,
  routeSlug: string,
  slugChangeRequest: BodyType<SlugChangeRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<RouteDetailDto>(
    {
      url: `/api/teams/${slug}/routes/${routeSlug}/slug`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: slugChangeRequest,
    },
    options
  )
}

export const getChangeRouteSlugMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof changeRouteSlug>>,
    TError,
    { slug: string; routeSlug: string; data: BodyType<SlugChangeRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof changeRouteSlug>>,
  TError,
  { slug: string; routeSlug: string; data: BodyType<SlugChangeRequest> },
  TContext
> => {
  const mutationKey = ['changeRouteSlug']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof changeRouteSlug>>,
    { slug: string; routeSlug: string; data: BodyType<SlugChangeRequest> }
  > = (props) => {
    const { slug, routeSlug, data } = props ?? {}

    return changeRouteSlug(slug, routeSlug, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ChangeRouteSlugMutationResult = NonNullable<Awaited<ReturnType<typeof changeRouteSlug>>>
export type ChangeRouteSlugMutationBody = BodyType<SlugChangeRequest>
export type ChangeRouteSlugMutationError = ErrorType<ErrorResponse>

/**
 * @summary Change route slug
 */
export const useChangeRouteSlug = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof changeRouteSlug>>,
      TError,
      { slug: string; routeSlug: string; data: BodyType<SlugChangeRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof changeRouteSlug>>,
  TError,
  { slug: string; routeSlug: string; data: BodyType<SlugChangeRequest> },
  TContext
> => {
  const mutationOptions = getChangeRouteSlugMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
