// GENERATED by scripts/generate-brand-colors.mjs — edit contracts/brand-colors.yaml instead.
// ignore_for_file: type=lint

// `Visibility` est à la fois un widget Flutter et un enum du contrat : ici
// c'est l'enum qui compte.
import 'package:flutter/painting.dart';

import '../../api/generated/models/publication_type.dart';
import '../../api/generated/models/ad_type.dart';
import '../../api/generated/models/status.dart';
import '../../api/generated/models/team_role.dart';
import '../../api/generated/models/surface_type.dart';
import '../../api/generated/models/visibility.dart';
import '../../api/generated/models/climb_category.dart';
import 'enum_colors.dart';
import 'pdl_colors.dart';

/// Les familles du code couleur métier. Le rendu de chacune est écrit à la
/// main dans `enum_colors.dart` (`PdlFamilyTone`).
enum PdlFamily { indigo, blue, green, red, yellow, orange, grape, teal, gray }

extension PublicationTypeTone on PublicationType {
  PdlFamily get family => switch (this) {
    PublicationType.ride => PdlFamily.blue,
    PublicationType.post => PdlFamily.grape,
    PublicationType.trip => PdlFamily.teal,
    PublicationType.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.soft(c);
}

extension AdTypeTone on AdType {
  PdlFamily get family => switch (this) {
    AdType.sale => PdlFamily.green,
    AdType.rental => PdlFamily.indigo,
    AdType.wanted => PdlFamily.orange,
    AdType.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.soft(c);
}

extension StatusTone on Status {
  PdlFamily get family => switch (this) {
    Status.draft => PdlFamily.gray,
    Status.published => PdlFamily.green,
    Status.cancelled => PdlFamily.red,
    Status.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.soft(c);
}

extension TeamRoleTone on TeamRole {
  PdlFamily get family => switch (this) {
    TeamRole.member => PdlFamily.gray,
    TeamRole.organizer => PdlFamily.blue,
    TeamRole.admin => PdlFamily.grape,
    TeamRole.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.soft(c);
}

extension SurfaceTypeTone on SurfaceType {
  PdlFamily get family => switch (this) {
    SurfaceType.road => PdlFamily.gray,
    SurfaceType.gravel => PdlFamily.orange,
    SurfaceType.mtb => PdlFamily.green,
    SurfaceType.mixed => PdlFamily.teal,
    SurfaceType.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.soft(c);
}

extension VisibilityTone on Visibility {
  PdlFamily get family => switch (this) {
    Visibility.team => PdlFamily.gray,
    Visibility.publicUnlisted => PdlFamily.orange,
    Visibility.public => PdlFamily.blue,
    Visibility.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.soft(c);
}

extension ClimbCategoryTone on ClimbCategory {
  PdlFamily get family => switch (this) {
    ClimbCategory.hc => PdlFamily.grape,
    ClimbCategory.cat1 => PdlFamily.red,
    ClimbCategory.cat2 => PdlFamily.orange,
    ClimbCategory.cat3 => PdlFamily.yellow,
    ClimbCategory.cat4 => PdlFamily.green,
    ClimbCategory.$unknown => PdlFamily.gray,
  };

  PdlTone tone(PdlColors c) => family.filled(c);
}

/// Fond d'une carte sans photo, à 135° (haut gauche → bas droite).
abstract final class PdlFallbackGradients {
  static const LinearGradient ride = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: <Color>[Color(0xFF228BE6), Color(0xFF22B8CF)],
  );
  static const LinearGradient post = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: <Color>[Color(0xFFBE4BDB), Color(0xFFF06595)],
  );
  static const LinearGradient trip = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: <Color>[Color(0xFF12B886), Color(0xFF51CF66)],
  );
  static const LinearGradient team = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: <Color>[Color(0xFF7950F2), Color(0xFF5C7CFA)],
  );
  static const LinearGradient ad = LinearGradient(
    begin: Alignment.topLeft,
    end: Alignment.bottomRight,
    colors: <Color>[Color(0xFFFF922B), Color(0xFFFFD43B)],
  );
}
