/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type { ErrorResponse, GarminRoutesResponse, GetRoutesParams } from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get routes for authenticated user. Prioritizes routes from upcoming rides, then latest routes from user's teams.
 * @summary List routes for user
 */
export const getRoutes = (
  params?: GetRoutesParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<GarminRoutesResponse>(
    { url: `/api/garmin/routes`, method: 'GET', params, signal },
    options
  )
}

export const getGetRoutesQueryKey = (params?: GetRoutesParams) => {
  return [`/api/garmin/routes`, ...(params ? [params] : [])] as const
}

export const getGetRoutesQueryOptions = <
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRoutesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoutes>>> = ({ signal }) =>
    getRoutes(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getRoutes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoutesQueryResult = NonNullable<Awaited<ReturnType<typeof getRoutes>>>
export type GetRoutesQueryError = ErrorType<ErrorResponse>

export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: undefined | GetRoutesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoutes>>,
          TError,
          Awaited<ReturnType<typeof getRoutes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRoutes>>,
          TError,
          Awaited<ReturnType<typeof getRoutes>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List routes for user
 */

export function useGetRoutes<
  TData = Awaited<ReturnType<typeof getRoutes>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: GetRoutesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRoutes>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRoutesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Download route as FIT file for Garmin GPS
 * @summary Download FIT file
 */
export const downloadFit = (
  teamSlug: string,
  routeSlug: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<unknown>(
    { url: `/api/garmin/routes/${teamSlug}/${routeSlug}/fit`, method: 'GET', signal },
    options
  )
}

export const getDownloadFitQueryKey = (teamSlug?: string, routeSlug?: string) => {
  return [`/api/garmin/routes/${teamSlug}/${routeSlug}/fit`] as const
}

export const getDownloadFitQueryOptions = <
  TData = Awaited<ReturnType<typeof downloadFit>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFit>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getDownloadFitQueryKey(teamSlug, routeSlug)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadFit>>> = ({ signal }) =>
    downloadFit(teamSlug, routeSlug, requestOptions, signal)

  return {
    queryKey,
    queryFn,
    enabled: !!(teamSlug && routeSlug),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof downloadFit>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }
}

export type DownloadFitQueryResult = NonNullable<Awaited<ReturnType<typeof downloadFit>>>
export type DownloadFitQueryError = ErrorType<ErrorResponse>

export function useDownloadFit<
  TData = Awaited<ReturnType<typeof downloadFit>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  routeSlug: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFit>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFit>>,
          TError,
          Awaited<ReturnType<typeof downloadFit>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFit<
  TData = Awaited<ReturnType<typeof downloadFit>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFit>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadFit>>,
          TError,
          Awaited<ReturnType<typeof downloadFit>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadFit<
  TData = Awaited<ReturnType<typeof downloadFit>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFit>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download FIT file
 */

export function useDownloadFit<
  TData = Awaited<ReturnType<typeof downloadFit>>,
  TError = ErrorType<ErrorResponse>,
>(
  teamSlug: string,
  routeSlug: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadFit>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDownloadFitQueryOptions(teamSlug, routeSlug, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
