ALTER TABLE teams ADD COLUMN visibility_editable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN joinable BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE teams ADD COLUMN add_member_allowed BOOLEAN NOT NULL DEFAULT FALSE;
