ALTER TABLE assets DROP CONSTRAINT IF EXISTS assets_type_check;
ALTER TABLE assets ADD CONSTRAINT assets_type_check
  CHECK (type IN (
    'LOGO', 'IMAGE', 'ATTACHMENT',
    'ROUTE_ORIGINAL_GPX', 'ROUTE_FILTERED_GPX', 'ROUTE_FIT',
    'ROUTE_THUMBNAIL_LIGHT', 'ROUTE_THUMBNAIL_DARK',
    'RIDE_THUMBNAIL_LIGHT', 'RIDE_THUMBNAIL_DARK',
    'TRIP_THUMBNAIL_LIGHT', 'TRIP_THUMBNAIL_DARK'
  ));
