/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get paginated list of team members
 * @summary Get team members
 */
export const getMembersParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

export const getMembersQueryPageDefault = 0
export const getMembersQuerySizeDefault = 50

export const getMembersQueryParams = zod.object({
  page: zod.number().optional().describe('Page number'),
  size: zod.number().default(getMembersQuerySizeDefault).describe('Page size'),
})

export const getMembersResponse = zod
  .object({
    members: zod
      .array(
        zod
          .object({
            team: zod
              .object({
                id: zod.string().describe('Team ID (TSID)'),
                name: zod.string().describe('Team name'),
                slug: zod.string().describe('Team URL slug'),
                visibility: zod.enum(['TEAM', 'PUBLIC']),
              })
              .describe('Team information'),
            id: zod.string().describe('Membership ID (TSID)'),
            user: zod
              .object({
                id: zod.string().describe('User ID (TSID)'),
                displayName: zod.string().describe('User display name'),
                avatarUrl: zod.string().optional().describe('User avatar URL'),
              })
              .describe('Public user information (limited fields)'),
            role: zod.enum(['MEMBER', 'ORGANIZER', 'ADMIN']),
            joinedAt: zod.iso.datetime({}).optional(),
          })
          .describe('Team member information')
      )
      .describe('List of members'),
    total: zod.number().describe('Total number of members'),
    page: zod.number().describe('Current page number'),
    size: zod.number().describe('Page size'),
  })
  .describe('Paginated member list response')

/**
 * Add a member to the team. Requires ADMIN role on team.
 * @summary Add team member
 */
export const addMemberParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

export const addMemberBody = zod
  .object({
    userId: zod.string().describe('User ID (TSID) to add'),
    role: zod.enum(['MEMBER', 'ORGANIZER', 'ADMIN']).optional(),
  })
  .describe('Request to add a member to the team')

/**
 * Request to join a team
 * @summary Join team
 */
export const joinTeamParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

/**
 * Leave a team
 * @summary Leave team
 */
export const leaveTeamParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

/**
 * Update a team member's role. Requires ADMIN role.
 * @summary Update member role
 */
export const updateMemberRoleParams = zod.object({
  memberId: zod.string().describe('Member user ID (TSID)'),
  teamSlug: zod.string().describe('Team URL slug'),
})

export const updateMemberRoleBody = zod
  .object({
    role: zod.enum(['MEMBER', 'ORGANIZER', 'ADMIN']),
  })
  .describe("Request to update a member's role")

export const updateMemberRoleResponse = zod
  .object({
    team: zod
      .object({
        id: zod.string().describe('Team ID (TSID)'),
        name: zod.string().describe('Team name'),
        slug: zod.string().describe('Team URL slug'),
        visibility: zod.enum(['TEAM', 'PUBLIC']),
      })
      .describe('Team information'),
    id: zod.string().describe('Membership ID (TSID)'),
    user: zod
      .object({
        id: zod.string().describe('User ID (TSID)'),
        displayName: zod.string().describe('User display name'),
        avatarUrl: zod.string().optional().describe('User avatar URL'),
      })
      .describe('Public user information (limited fields)'),
    role: zod.enum(['MEMBER', 'ORGANIZER', 'ADMIN']),
    joinedAt: zod.iso.datetime({}).optional(),
  })
  .describe('Team member information')

/**
 * Remove a member from the team. Requires ADMIN role.
 * @summary Remove team member
 */
export const removeMemberParams = zod.object({
  memberId: zod.string().describe('Member user ID (TSID)'),
  teamSlug: zod.string().describe('Team URL slug'),
})
