/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GpsServiceType } from './gpsServiceType'
import type { Instant } from './instant'

/**
 * Admin GPS credential view (without secret)
 */
export interface AdminGpsCredentialDto {
  /** Credential ID (TSID) */
  id: string
  /** GPS service type */
  serviceType: GpsServiceType
  /** OAuth client ID */
  clientId: string
  /** Whether credential is active */
  active: boolean
  /** Credential creation timestamp */
  createdAt: Instant
}
