/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type AdminListTeamsParams = {
  /**
   * Filter by domain ID
   */
  domainId?: string
  /**
   * Page number (0-indexed)
   */
  page?: number
  /**
   * Page size
   */
  size?: number
}
