/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { AdminDomainDto } from './adminDomainDto'

/**
 * Paginated admin domain list response
 */
export interface AdminDomainListResponse {
  /** List of domains */
  domains: AdminDomainDto[]
  /** Total number of domains */
  total: number
  /** Current page number */
  page: number
  /** Page size */
  size: number
}
