/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { AdminUserDto } from './adminUserDto'

/**
 * Paginated admin user list response
 */
export interface AdminUserListResponse {
  /** List of users */
  users: AdminUserDto[]
  /** Total number of users */
  total: number
  /** Current page number */
  page: number
  /** Page size */
  size: number
}
