/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MediaDto } from './mediaDto'
import type { Status } from './status'
import type { AdType } from './adType'
import type { RentalPeriod } from './rentalPeriod'

/**
 * Ad request
 */
export interface AdRequest {
  /**
   * Ad name
   * @minLength 1
   * @maxLength 200
   * @pattern \S
   */
  name: string
  /** Ad description */
  media: MediaDto
  /** Ad status */
  status: Status
  /** Ad type */
  adType: AdType
  /** Price (optional, null for 'contact for price') */
  price?: number
  /** Rental period (required for RENTAL type) */
  rentalPeriod?: RentalPeriod
  /**
   * Location description
   * @maxLength 200
   */
  locationDescription?: string
}
