/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type AdType = (typeof AdType)[keyof typeof AdType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdType = {
  SALE: 'SALE',
  RENTAL: 'RENTAL',
  WANTED: 'WANTED',
} as const
