/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type AllEntityType = (typeof AllEntityType)[keyof typeof AllEntityType]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AllEntityType = {
  TEAM: 'TEAM',
  USER: 'USER',
  USER_TEAM: 'USER_TEAM',
  RIDE_TEMPLATE: 'RIDE_TEMPLATE',
  RIDE_TEMPLATE_GROUP: 'RIDE_TEMPLATE_GROUP',
  PLACE: 'PLACE',
  COMMENT: 'COMMENT',
  ASSET: 'ASSET',
  TRIP: 'TRIP',
  TRIP_STAGE: 'TRIP_STAGE',
  ROUTE: 'ROUTE',
  RIDE: 'RIDE',
  RIDE_GROUP: 'RIDE_GROUP',
  AD: 'AD',
  POST: 'POST',
  TEAM_PAGE: 'TEAM_PAGE',
} as const
