/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto'

/**
 * Authentication response
 */
export interface AuthResponse {
  /** JWT access token */
  accessToken?: string
  /** Token expiry in seconds */
  expiresIn?: number
  /** Authenticated user */
  user?: UserDto
  /** Refresh token (for mobile clients) */
  refreshToken?: string
}
