/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarEventDto } from './calendarEventDto'

/**
 * Calendar events response
 */
export interface CalendarEventsResponse {
  /** List of calendar events */
  events: CalendarEventDto[]
}
