/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type CalendarEventType = (typeof CalendarEventType)[keyof typeof CalendarEventType]

export const CalendarEventType = {
  RIDE: 'RIDE',
  TRIP_STAGE: 'TRIP_STAGE',
} as const
