/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Calendar token information
 */
export interface CalendarTokenDto {
  /** ICS feed token (include in URL) */
  token: string
  /** Global ICS feed URL */
  globalFeedUrl: string
  /** Team-specific feed URL template */
  teamFeedUrlTemplate: string
}
