/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { CommentDto } from './commentDto'

/**
 * List of comments response
 */
export interface CommentListResponse {
  /** List of comments (top-level only, with nested replies) */
  items: CommentDto[]
  /** Total count including replies */
  total: number
}
