/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Complete device authorization request
 */
export interface CompleteRequest {
  /** User code from device display */
  userCode: string
  /** Authenticated user ID (TSID string) */
  userId: string
}
