/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GpsServiceType } from './gpsServiceType'

/**
 * Request to create a new GPS credential
 */
export interface CreateGpsCredentialRequest {
  /** GPS service type */
  serviceType: GpsServiceType
  /**
   * OAuth client ID
   * @maxLength 255
   * @pattern \S
   */
  clientId: string
  /**
   * OAuth client secret (nullable for PKCE services)
   * @maxLength 500
   */
  clientSecret?: string
  /** Whether credential is active */
  active?: boolean
}
