/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Device auth request
 */
export interface DeviceRequest {
  /** Client ID (optional, defaults to 'karoo-device') */
  clientId?: string
}
