/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type DeviceListRoutesParams = {
  /**
   * User's current latitude (for proximity sorting)
   */
  lat?: number
  /**
   * User's current longitude (for proximity sorting)
   */
  lon?: number
}
