/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Route entry within a ride for device applications
 */
export interface DeviceRideEntryDto {
  /** Route slug */
  routeSlug: string
  /** Route name */
  routeName: string
  /** Group name (null for ride-level route) */
  groupName?: string
  /** Distance in meters */
  distance: number
  /** Elevation gain in meters */
  elevationGain: number
  /** Start latitude */
  startLat?: number
  /** Start longitude */
  startLon?: number
}
