/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceRideDto } from './deviceRideDto'
import type { DeviceRouteDto } from './deviceRouteDto'

/**
 * Response containing rides and routes for device applications
 */
export interface DeviceRoutesResponse {
  /** Upcoming rides with route entries */
  rides: DeviceRideDto[]
  /** Latest standalone routes */
  routes: DeviceRouteDto[]
}
