/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorValidationDetailsType } from './errorValidationDetailsType'
import type { FieldError } from './fieldError'

export interface ErrorValidationDetails {
  type: ErrorValidationDetailsType
  /** Field Errors */
  fieldErrors: FieldError[]
}
