/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GarminRouteDto } from './garminRouteDto'

/**
 * List of routes for Garmin device
 */
export interface GarminRoutesResponse {
  /** Routes list */
  routes: GarminRouteDto[]
}
