/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Garmin OAuth callback from frontend
 */
export interface GarminCallbackRequest {
  /**
   * User's access token from frontend auth
   * @pattern \S
   */
  accessToken: string
  /**
   * Original redirect URI from authorize request
   * @pattern \S
   */
  redirectUri: string
  /** State parameter from authorize request */
  state?: string
}
