/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type GetEventsParams = {
  /**
   * Start date (ISO 8601)
   */
  from?: string
  /**
   * End date (ISO 8601)
   */
  to?: string
}
