/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { LocalTime } from './localTime'

/**
 * Ride group creation request
 */
export interface GroupRequest {
  /** id */
  id?: string
  /**
   * Group name
   * @minLength 1
   * @maxLength 200
   * @pattern \S
   */
  name: string
  time?: LocalTime
  /**
   * Average speed in km/h
   */
  averageSpeed?: number
  /**
   * Maximum participants
   */
  maxParticipants?: number
  /** Route slug for this group */
  routeSlug?: string
}
