/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Karoo OAuth token request
 */
export interface KarooTokenRequest {
  /**
   * Grant type: 'urn:ietf:params:oauth:grant-type:device_code' or 'refresh_token'
   * @pattern \S
   */
  grantType: string
  /** Device code (for device_code grant) */
  deviceCode?: string
  /** Refresh token (for refresh_token grant) */
  refreshToken?: string
}
