/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Keycloak configuration
 */
export interface KeycloakConfig {
  /** Keycloak server URL */
  url: string
  /** Keycloak realm name */
  realm: string
  /** Keycloak client ID */
  clientId: string
}
