/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type ListDomainsParams = {
  /**
   * Page number (0-indexed)
   */
  page?: number
  /**
   * Page size
   */
  size?: number
}
