/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Magic link request
 */
export interface MagicLinkRequest {
  /**
   * Email address
   * @maxLength 250
   * @pattern \S
   */
  email: string
}
