/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MemberDto } from './memberDto'

/**
 * Paginated member list response
 */
export interface MemberListResponse {
  /** List of members */
  members: MemberDto[]
  /** Total number of members */
  total: number
  /** Current page number */
  page: number
  /** Page size */
  size: number
}
