/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { TeamPublicationDto } from './teamPublicationDto'
import type { PublicUserDto } from './publicUserDto'
import type { TeamRole } from './teamRole'
import type { Instant } from './instant'

/**
 * Team member information
 */
export interface MemberDto {
  /** Team */
  team: TeamPublicationDto
  /** Membership ID (TSID) */
  id: string
  /** User */
  user: PublicUserDto
  /** Member role */
  role: TeamRole
  /** When the user joined the team */
  joinedAt?: Instant
}
