/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { NotFoundDetailsType } from './notFoundDetailsType'
import type { EntityType } from './entityType'
import type { SearchedBy } from './searchedBy'

export interface NotFoundDetails {
  type: NotFoundDetailsType
  /** Entity type */
  entityType: EntityType
  /** Search type */
  searchedBy: SearchedBy
  /** id/slug */
  id: string
}
