/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PlaceRequestGeometryType } from './placeRequestGeometryType'

/**
 * Geographic coordinates [longitude, latitude]
 */
export type PlaceRequestGeometry = {
  type: PlaceRequestGeometryType
  /** Coordinates [longitude, latitude] */
  coordinates: number[]
}
