/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PlaceRequestCoordinatesType } from './placeRequestCoordinatesType'

/**
 * Geographic coordinates [longitude, latitude]
 */
export type PlaceRequestCoordinates = {
  type: PlaceRequestCoordinatesType
  /** Coordinates [longitude, latitude] */
  coordinates: number[]
}
