/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Place create/update request
 */
export interface PlaceRequest {
  /**
   * Place name
   * @minLength 3
   * @maxLength 200
   * @pattern \S
   */
  name: string
  /** Address */
  address?: string
  /** External link (e.g., Google Maps URL) */
  link?: string
  /** Can be used as ride start point */
  startPlace: boolean
  /** Can be used as ride end point */
  endPlace: boolean
  /** Geographic coordinates [longitude, latitude] */
  coordinates?: number[]
}
