/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type PlatformRole = (typeof PlatformRole)[keyof typeof PlatformRole]

export const PlatformRole = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
} as const
