/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type PlatformRole = (typeof PlatformRole)[keyof typeof PlatformRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlatformRole = {
  PLATFORM_ADMIN: 'PLATFORM_ADMIN',
} as const
