/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MediaDto } from './mediaDto'
import type { Instant } from './instant'
import type { Status } from './status'
import type { Visibility } from './visibility'

/**
 * Post request
 */
export interface PostRequest {
  /**
   * Post name
   * @minLength 3
   * @maxLength 200
   * @pattern \S
   */
  name: string
  /** Post description */
  media: MediaDto
  /** Post date/time */
  dateTime: Instant
  /** Post status */
  status: Status
  /** Visibility level */
  visibility: Visibility
  /** Publication timestamp (for scheduled publishing) */
  publishAt?: Instant
}
