/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { PublicationDto } from './publicationDto'

/**
 * Paginated publication list response
 */
export interface PublicationListResponse {
  /** List of publications */
  publications: PublicationDto[]
  /** Total number of publications */
  total: number
  /** Current page number */
  page: number
  /** Page size */
  size: number
}
