/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { LocalTime } from './localTime'

/**
 * Ride template group request
 */
export interface RideTemplateGroupRequest {
  /** Group ID (TSID) - only for updates */
  id?: string
  /**
   * Group name
   * @minLength 1
   * @maxLength 200
   * @pattern \S
   */
  name: string
  time?: LocalTime
  /** Average speed in km/h */
  averageSpeed?: number
  /** Maximum participants */
  maxParticipants?: number
}
