/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { Visibility } from './visibility'
import type { Status } from './status'
import type { Instant } from './instant'
import type { RideTemplateGroupDto } from './rideTemplateGroupDto'

/**
 * Ride template response
 */
export interface RideTemplateDto {
  /** Template ID (TSID) */
  id: string
  /** Template slug */
  slug: string
  /** Template name */
  name: string
  /** Template description (markdown) */
  markdown?: string
  /** Visibility level */
  visibility: Visibility
  /** Default status */
  status: Status
  /** Creation timestamp */
  createdAt: Instant
  /** Last update timestamp */
  updatedAt: Instant
  /** Number of groups */
  groupCount: number
  /** Template groups */
  groups: RideTemplateGroupDto[]
}
