/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { RideTemplateDto } from './rideTemplateDto'

/**
 * Paginated ride template list response
 */
export interface RideTemplateListResponse {
  /** List of templates */
  templates: RideTemplateDto[]
  /** Total number of templates */
  total: number
  /** Current page number */
  page: number
  /** Page size */
  size: number
}
