/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { Visibility } from './visibility'
import type { Status } from './status'
import type { RideTemplateGroupRequest } from './rideTemplateGroupRequest'

/**
 * Ride template request
 */
export interface RideTemplateRequest {
  /**
   * Template name
   * @minLength 1
   * @maxLength 200
   * @pattern \S
   */
  name: string
  /** Template description (markdown) */
  markdown: string
  /** Visibility level */
  visibility: Visibility
  /** Default status for rides created from this template */
  status: Status
  /** Template groups */
  groups: RideTemplateGroupRequest[]
}
