/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { MediaDto } from './mediaDto'
import type { SurfaceType } from './surfaceType'
import type { Visibility } from './visibility'
import type { GeoPoint } from './geoPoint'

/**
 * Route update request
 */
export interface RouteRequest {
  /**
   * Route name
   * @minLength 3
   * @maxLength 200
   * @pattern \S
   */
  name: string
  /** Media */
  media: MediaDto
  /** Surface type */
  surfaceType: SurfaceType
  /** Whether the route is publicly visible */
  visibility: Visibility
  /** Points from frontend routing */
  points?: GeoPoint[]
}
