/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { GeoPoint } from './geoPoint'
import type { RouterProfile } from './routerProfile'

export interface RouterRequest {
  from: GeoPoint
  to: GeoPoint
  profile: RouterProfile
}
