/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type SearchUsersParams = {
  /**
   * Maximum results (max 20)
   */
  limit?: number
  /**
   * Search query
   */
  q?: string
}
