/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * Slug change request
 */
export interface SlugChangeRequest {
  /**
   * New slug (lowercase letters, numbers, and hyphens only)
   * @maxLength 200
   * @pattern ^[a-z0-9]+(-[a-z0-9]+)*$
   */
  slug: string;
}
