/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type TeamRole = (typeof TeamRole)[keyof typeof TeamRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamRole = {
  ADMIN: 'ADMIN',
  ORGANIZER: 'ORGANIZER',
  MEMBER: 'MEMBER',
} as const
