/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type TeamDetailDtoGeometryType =
  (typeof TeamDetailDtoGeometryType)[keyof typeof TeamDetailDtoGeometryType]

export const TeamDetailDtoGeometryType = {
  Point: 'Point',
} as const
