/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ClimbDto } from './climbDto'
import type { GeoJsonLineString } from './geoJsonLineString'

/**
 * GPX track with track points
 */
export interface TrackDto {
  line: GeoJsonLineString
  /** List of climbs on the route */
  climbs: ClimbDto[]
}
