/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import type { RouteRequest } from './routeRequest'

export type UpdateRouteBody = {
  route?: RouteRequest
  gpxFile?: Blob
}
