/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type Visibility = (typeof Visibility)[keyof typeof Visibility]

export const Visibility = {
  TEAM: 'TEAM',
  PUBLIC: 'PUBLIC',
} as const
