/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */

export type WindDirection = (typeof WindDirection)[keyof typeof WindDirection]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WindDirection = {
  NORTH: 'NORTH',
  NORTH_EAST: 'NORTH_EAST',
  EAST: 'EAST',
  SOUTH_EAST: 'SOUTH_EAST',
  SOUTH: 'SOUTH',
  SOUTH_WEST: 'SOUTH_WEST',
  WEST: 'WEST',
  NORTH_WEST: 'NORTH_WEST',
} as const
