/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get authenticated user's status including connected GPS services
 * @summary Get current user status
 */
export const DeviceGetMeResponse = zod
  .object({
    connectedGpsServices: zod
      .array(zod.enum(['HAMMERHEAD', 'GARMIN']))
      .describe('List of connected GPS services'),
  })
  .describe("Response containing user's device connection status")
