/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Called by frontend after user authenticates via OTP
 * @summary Complete device authorization
 */
export const karooCompleteBody = zod
  .object({
    userCode: zod.string().describe('User code from device display'),
    userId: zod.string().describe('Authenticated user ID (TSID string)'),
  })
  .describe('Complete device authorization request')

export const karooCompleteResponse = zod.unknown()

/**
 * Start device code flow - returns user code and verification URL
 * @summary Request device code
 */
export const deviceBody = zod
  .object({
    clientId: zod.string().optional().describe("Client ID (optional, defaults to 'karoo-device')"),
  })
  .describe('Device auth request')

export const deviceResponse = zod
  .object({
    deviceCode: zod.string().describe('Device code for polling'),
    userCode: zod.string().describe("User code to display (e.g., 'ABCD12')"),
    verificationUri: zod.string().describe('Verification URL for user to visit'),
    verificationUriComplete: zod.string().describe('Verification URL with user code embedded'),
    expiresIn: zod.number().describe('Code expiry in seconds'),
    interval: zod.number().describe('Minimum polling interval in seconds'),
  })
  .describe('Karoo device code response (RFC 8628)')

/**
 * Exchange device code or refresh token for access tokens. Returns 'authorization_pending' error while waiting for user.
 * @summary Exchange code for tokens
 */
export const karooTokenBodyGrantTypeRegExp = new RegExp('\\S')

export const karooTokenBody = zod
  .object({
    grantType: zod
      .string()
      .regex(karooTokenBodyGrantTypeRegExp)
      .describe("Grant type: 'urn:ietf:params:oauth:grant-type:device_code' or 'refresh_token'"),
    deviceCode: zod.string().optional().describe('Device code (for device_code grant)'),
    refreshToken: zod.string().optional().describe('Refresh token (for refresh_token grant)'),
  })
  .describe('Karoo OAuth token request')

export const karooTokenResponse = zod
  .object({
    accessToken: zod.string().describe('Access token'),
    tokenType: zod.string().describe("Token type (always 'Bearer')"),
    expiresIn: zod.number().describe('Token expiry in seconds'),
    refreshToken: zod.string().optional().describe('Refresh token'),
  })
  .describe('Karoo OAuth token response')

/**
 * Frontend uses this to verify user code before showing auth flow
 * @summary Check user code validity
 */
export const verifyQueryParams = zod.object({
  code: zod.string().optional(),
})

export const verifyResponse = zod
  .object({
    userCode: zod.string().describe('User code'),
    authorized: zod.boolean().optional().describe('Whether authorization is already completed'),
  })
  .describe('User code verification response')
