/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get all places for a team
 * @summary List places
 */
export const ListPlacesParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

export const listPlacesQueryPageDefault = 0
export const listPlacesQuerySizeDefault = 50

export const ListPlacesQueryParams = zod.object({
  page: zod.number().default(listPlacesQueryPageDefault).describe('Page number'),
  size: zod.number().default(listPlacesQuerySizeDefault).describe('Page size'),
})

export const ListPlacesResponse = zod
  .object({
    places: zod
      .array(
        zod.object({
          id: zod.string().describe('Place ID (TSID)'),
          name: zod.string(),
          address: zod.string().optional(),
          link: zod.string().optional(),
          startPlace: zod.boolean(),
          endPlace: zod.boolean(),
          geometry: zod
            .object({
              type: zod.enum(['Point']),
              coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
            })
            .optional()
            .describe('Location coordinates [longitude, latitude]'),
        })
      )
      .describe('List of places'),
    total: zod.number().describe('Total number of places'),
    page: zod.number().describe('Current page number'),
    size: zod.number().describe('Page size'),
  })
  .describe('Paginated place list response')

/**
 * Create a new place for the team
 * @summary Create place
 */
export const CreatePlaceParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

export const createPlaceBodyNameMax = 200

export const createPlaceBodyNameRegExp = new RegExp('\\S')
export const createPlaceBodyAddressMin = 3
export const createPlaceBodyAddressMax = 200

export const createPlaceBodyLinkMin = 3
export const createPlaceBodyLinkMax = 200

export const CreatePlaceBody = zod
  .object({
    name: zod
      .string()
      .min(1)
      .max(createPlaceBodyNameMax)
      .regex(createPlaceBodyNameRegExp)
      .describe('Place name'),
    address: zod
      .string()
      .min(createPlaceBodyAddressMin)
      .max(createPlaceBodyAddressMax)
      .optional()
      .describe('Address'),
    link: zod
      .string()
      .min(createPlaceBodyLinkMin)
      .max(createPlaceBodyLinkMax)
      .optional()
      .describe('External link (e.g., Google Maps URL)'),
    startPlace: zod.boolean().describe('Can be used as ride start point'),
    endPlace: zod.boolean().describe('Can be used as ride end point'),
    geometry: zod
      .object({
        type: zod.enum(['Point']),
        coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
      })
      .optional()
      .describe('Geographic coordinates [longitude, latitude]'),
  })
  .describe('Place create\/update request')

/**
 * Update an existing place
 * @summary Update place
 */
export const UpdatePlaceParams = zod.object({
  placeId: zod.string().describe('Place ID (TSID)'),
  teamSlug: zod.string().describe('Team URL slug'),
})

export const updatePlaceBodyNameMax = 200

export const updatePlaceBodyNameRegExp = new RegExp('\\S')
export const updatePlaceBodyAddressMin = 3
export const updatePlaceBodyAddressMax = 200

export const updatePlaceBodyLinkMin = 3
export const updatePlaceBodyLinkMax = 200

export const UpdatePlaceBody = zod
  .object({
    name: zod
      .string()
      .min(1)
      .max(updatePlaceBodyNameMax)
      .regex(updatePlaceBodyNameRegExp)
      .describe('Place name'),
    address: zod
      .string()
      .min(updatePlaceBodyAddressMin)
      .max(updatePlaceBodyAddressMax)
      .optional()
      .describe('Address'),
    link: zod
      .string()
      .min(updatePlaceBodyLinkMin)
      .max(updatePlaceBodyLinkMax)
      .optional()
      .describe('External link (e.g., Google Maps URL)'),
    startPlace: zod.boolean().describe('Can be used as ride start point'),
    endPlace: zod.boolean().describe('Can be used as ride end point'),
    geometry: zod
      .object({
        type: zod.enum(['Point']),
        coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
      })
      .optional()
      .describe('Geographic coordinates [longitude, latitude]'),
  })
  .describe('Place create\/update request')

export const UpdatePlaceResponse = zod.object({
  id: zod.string().describe('Place ID (TSID)'),
  name: zod.string(),
  address: zod.string().optional(),
  link: zod.string().optional(),
  startPlace: zod.boolean(),
  endPlace: zod.boolean(),
  geometry: zod
    .object({
      type: zod.enum(['Point']),
      coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
    })
    .optional()
    .describe('Location coordinates [longitude, latitude]'),
})

/**
 * Get a specific place by ID
 * @summary Get place details
 */
export const GetPlaceParams = zod.object({
  placeId: zod.string().describe('Place ID (TSID)'),
  teamSlug: zod.string().describe('Team URL slug'),
})

export const GetPlaceResponse = zod.object({
  id: zod.string().describe('Place ID (TSID)'),
  name: zod.string(),
  address: zod.string().optional(),
  link: zod.string().optional(),
  startPlace: zod.boolean(),
  endPlace: zod.boolean(),
  geometry: zod
    .object({
      type: zod.enum(['Point']),
      coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
    })
    .optional()
    .describe('Location coordinates [longitude, latitude]'),
})

/**
 * Soft delete a place
 * @summary Delete place
 */
export const DeletePlaceParams = zod.object({
  placeId: zod.string().describe('Place ID (TSID)'),
  teamSlug: zod.string().describe('Team URL slug'),
})
