/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get all places for a team
 * @summary List places
 */
export const listPlacesParams = zod.object({
  slug: zod.string().describe('Team URL slug'),
})

export const listPlacesQueryPageDefault = 0
export const listPlacesQuerySizeDefault = 50

export const listPlacesQueryParams = zod.object({
  page: zod.number().optional().describe('Page number'),
  size: zod.number().default(listPlacesQuerySizeDefault).describe('Page size'),
})

export const listPlacesResponse = zod
  .object({
    places: zod
      .array(
        zod.object({
          id: zod.string().describe('Place ID (TSID)'),
          name: zod.string(),
          address: zod.string().optional(),
          link: zod.string().optional(),
          startPlace: zod.boolean(),
          endPlace: zod.boolean(),
          geometry: zod
            .object({
              type: zod.enum(['Point']),
              coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
            })
            .optional()
            .describe('GeoJSON Point geometry'),
        })
      )
      .describe('List of places'),
    total: zod.number().describe('Total number of places'),
    page: zod.number().describe('Current page number'),
    size: zod.number().describe('Page size'),
  })
  .describe('Paginated place list response')

/**
 * Create a new place for the team
 * @summary Create place
 */
export const createPlaceParams = zod.object({
  slug: zod.string().describe('Team URL slug'),
})

export const createPlaceBody = zod
  .object({
    name: zod.string().describe('Place name'),
    address: zod.string().optional().describe('Address'),
    link: zod.string().optional().describe('External link (e.g., Google Maps URL)'),
    startPlace: zod.boolean().describe('Can be used as ride start point'),
    endPlace: zod.boolean().describe('Can be used as ride end point'),
    coordinates: zod
      .array(zod.number())
      .optional()
      .describe('Geographic coordinates [longitude, latitude]'),
  })
  .describe('Place create/update request')

/**
 * Update an existing place
 * @summary Update place
 */
export const updatePlaceParams = zod.object({
  placeId: zod.string().describe('Place ID (TSID)'),
  slug: zod.string().describe('Team URL slug'),
})

export const updatePlaceBody = zod
  .object({
    name: zod.string().describe('Place name'),
    address: zod.string().optional().describe('Address'),
    link: zod.string().optional().describe('External link (e.g., Google Maps URL)'),
    startPlace: zod.boolean().describe('Can be used as ride start point'),
    endPlace: zod.boolean().describe('Can be used as ride end point'),
    coordinates: zod
      .array(zod.number())
      .optional()
      .describe('Geographic coordinates [longitude, latitude]'),
  })
  .describe('Place create/update request')

export const updatePlaceResponse = zod.object({
  id: zod.string().describe('Place ID (TSID)'),
  name: zod.string(),
  address: zod.string().optional(),
  link: zod.string().optional(),
  startPlace: zod.boolean(),
  endPlace: zod.boolean(),
  geometry: zod
    .object({
      type: zod.enum(['Point']),
      coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
    })
    .optional()
    .describe('GeoJSON Point geometry'),
})

/**
 * Get a specific place by ID
 * @summary Get place details
 */
export const getPlaceParams = zod.object({
  placeId: zod.string().describe('Place ID (TSID)'),
  slug: zod.string().describe('Team URL slug'),
})

export const getPlaceResponse = zod.object({
  id: zod.string().describe('Place ID (TSID)'),
  name: zod.string(),
  address: zod.string().optional(),
  link: zod.string().optional(),
  startPlace: zod.boolean(),
  endPlace: zod.boolean(),
  geometry: zod
    .object({
      type: zod.enum(['Point']),
      coordinates: zod.array(zod.number()).describe('Coordinates [longitude, latitude]'),
    })
    .optional()
    .describe('GeoJSON Point geometry'),
})

/**
 * Soft delete a place
 * @summary Delete place
 */
export const deletePlaceParams = zod.object({
  placeId: zod.string().describe('Place ID (TSID)'),
  slug: zod.string().describe('Team URL slug'),
})
