/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  AdminDomainDto,
  AdminDomainListResponse,
  AdminGpsCredentialDto,
  AdminStatsDto,
  CreateDomainRequest,
  CreateGpsCredentialRequest,
  ErrorResponse,
  ListDomainsParams,
  UpdateDomainRequest,
  UpdateGpsCredentialRequest,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Get a paginated list of all domains
 * @summary List all domains
 */
export const listDomains = (
  params?: ListDomainsParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdminDomainListResponse>(
    { url: `/api/admin/domains`, method: 'GET', params, signal },
    options
  )
}

export const getListDomainsQueryKey = (params?: ListDomainsParams) => {
  return [`/api/admin/domains`, ...(params ? [params] : [])] as const
}

export const getListDomainsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDomains>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  params?: ListDomainsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDomains>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListDomainsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDomains>>> = ({ signal }) =>
    listDomains(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDomains>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDomainsQueryResult = NonNullable<Awaited<ReturnType<typeof listDomains>>>
export type ListDomainsQueryError = ErrorType<void | ErrorResponse>

export function useListDomains<
  TData = Awaited<ReturnType<typeof listDomains>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  params: undefined | ListDomainsParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDomains>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDomains>>,
          TError,
          Awaited<ReturnType<typeof listDomains>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDomains<
  TData = Awaited<ReturnType<typeof listDomains>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  params?: ListDomainsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDomains>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDomains>>,
          TError,
          Awaited<ReturnType<typeof listDomains>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDomains<
  TData = Awaited<ReturnType<typeof listDomains>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  params?: ListDomainsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDomains>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List all domains
 */

export function useListDomains<
  TData = Awaited<ReturnType<typeof listDomains>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  params?: ListDomainsParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listDomains>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListDomainsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Create a new domain
 * @summary Create domain
 */
export const createDomain = (
  createDomainRequest: BodyType<CreateDomainRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdminDomainDto>(
    {
      url: `/api/admin/domains`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createDomainRequest,
      signal,
    },
    options
  )
}

export const getCreateDomainMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDomain>>,
    TError,
    { data: BodyType<CreateDomainRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDomain>>,
  TError,
  { data: BodyType<CreateDomainRequest> },
  TContext
> => {
  const mutationKey = ['createDomain']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDomain>>,
    { data: BodyType<CreateDomainRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return createDomain(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateDomainMutationResult = NonNullable<Awaited<ReturnType<typeof createDomain>>>
export type CreateDomainMutationBody = BodyType<CreateDomainRequest>
export type CreateDomainMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Create domain
 */
export const useCreateDomain = <TError = ErrorType<ErrorResponse | void>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createDomain>>,
      TError,
      { data: BodyType<CreateDomainRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createDomain>>,
  TError,
  { data: BodyType<CreateDomainRequest> },
  TContext
> => {
  const mutationOptions = getCreateDomainMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get overall platform statistics
 * @summary Get platform statistics
 */
export const getStats = (options?: SecondParameter<typeof axiosMutator>, signal?: AbortSignal) => {
  return axiosMutator<AdminStatsDto>(
    { url: `/api/admin/domains/stats`, method: 'GET', signal },
    options
  )
}

export const getGetStatsQueryKey = () => {
  return [`/api/admin/domains/stats`] as const
}

export const getGetStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<void | ErrorResponse>,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>
  request?: SecondParameter<typeof axiosMutator>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetStatsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({ signal }) =>
    getStats(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getStats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getStats>>>
export type GetStatsQueryError = ErrorType<void | ErrorResponse>

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get platform statistics
 */

export function useGetStats<
  TData = Awaited<ReturnType<typeof getStats>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Update domain information
 * @summary Update domain
 */
export const updateDomain = (
  domainId: string,
  updateDomainRequest: BodyType<UpdateDomainRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<AdminDomainDto>(
    {
      url: `/api/admin/domains/${domainId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateDomainRequest,
    },
    options
  )
}

export const getUpdateDomainMutationOptions = <
  TError = ErrorType<void | ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDomain>>,
    TError,
    { domainId: string; data: BodyType<UpdateDomainRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDomain>>,
  TError,
  { domainId: string; data: BodyType<UpdateDomainRequest> },
  TContext
> => {
  const mutationKey = ['updateDomain']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDomain>>,
    { domainId: string; data: BodyType<UpdateDomainRequest> }
  > = (props) => {
    const { domainId, data } = props ?? {}

    return updateDomain(domainId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateDomainMutationResult = NonNullable<Awaited<ReturnType<typeof updateDomain>>>
export type UpdateDomainMutationBody = BodyType<UpdateDomainRequest>
export type UpdateDomainMutationError = ErrorType<void | ErrorResponse>

/**
 * @summary Update domain
 */
export const useUpdateDomain = <TError = ErrorType<void | ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDomain>>,
      TError,
      { domainId: string; data: BodyType<UpdateDomainRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateDomain>>,
  TError,
  { domainId: string; data: BodyType<UpdateDomainRequest> },
  TContext
> => {
  const mutationOptions = getUpdateDomainMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Get detailed domain information
 * @summary Get domain details
 */
export const getDomain = (
  domainId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdminDomainDto>(
    { url: `/api/admin/domains/${domainId}`, method: 'GET', signal },
    options
  )
}

export const getGetDomainQueryKey = (domainId?: string) => {
  return [`/api/admin/domains/${domainId}`] as const
}

export const getGetDomainQueryOptions = <
  TData = Awaited<ReturnType<typeof getDomain>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomain>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDomainQueryKey(domainId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDomain>>> = ({ signal }) =>
    getDomain(domainId, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!domainId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDomain>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDomainQueryResult = NonNullable<Awaited<ReturnType<typeof getDomain>>>
export type GetDomainQueryError = ErrorType<void | ErrorResponse>

export function useGetDomain<
  TData = Awaited<ReturnType<typeof getDomain>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomain>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDomain>>,
          TError,
          Awaited<ReturnType<typeof getDomain>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDomain<
  TData = Awaited<ReturnType<typeof getDomain>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomain>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDomain>>,
          TError,
          Awaited<ReturnType<typeof getDomain>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDomain<
  TData = Awaited<ReturnType<typeof getDomain>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomain>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get domain details
 */

export function useGetDomain<
  TData = Awaited<ReturnType<typeof getDomain>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDomain>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDomainQueryOptions(domainId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Get all GPS credentials for a domain
 * @summary List GPS credentials
 */
export const listDomainGpsCredentials = (
  domainId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdminGpsCredentialDto[]>(
    { url: `/api/admin/domains/${domainId}/gps-credentials`, method: 'GET', signal },
    options
  )
}

export const getListDomainGpsCredentialsQueryKey = (domainId?: string) => {
  return [`/api/admin/domains/${domainId}/gps-credentials`] as const
}

export const getListDomainGpsCredentialsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDomainGpsCredentials>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDomainGpsCredentials>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListDomainGpsCredentialsQueryKey(domainId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDomainGpsCredentials>>> = ({
    signal,
  }) => listDomainGpsCredentials(domainId, requestOptions, signal)

  return { queryKey, queryFn, enabled: !!domainId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDomainGpsCredentials>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDomainGpsCredentialsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDomainGpsCredentials>>
>
export type ListDomainGpsCredentialsQueryError = ErrorType<void | ErrorResponse>

export function useListDomainGpsCredentials<
  TData = Awaited<ReturnType<typeof listDomainGpsCredentials>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDomainGpsCredentials>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDomainGpsCredentials>>,
          TError,
          Awaited<ReturnType<typeof listDomainGpsCredentials>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDomainGpsCredentials<
  TData = Awaited<ReturnType<typeof listDomainGpsCredentials>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDomainGpsCredentials>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDomainGpsCredentials>>,
          TError,
          Awaited<ReturnType<typeof listDomainGpsCredentials>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDomainGpsCredentials<
  TData = Awaited<ReturnType<typeof listDomainGpsCredentials>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDomainGpsCredentials>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List GPS credentials
 */

export function useListDomainGpsCredentials<
  TData = Awaited<ReturnType<typeof listDomainGpsCredentials>>,
  TError = ErrorType<void | ErrorResponse>,
>(
  domainId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listDomainGpsCredentials>>, TError, TData>
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListDomainGpsCredentialsQueryOptions(domainId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}

/**
 * Create a new GPS credential for a domain
 * @summary Create GPS credential
 */
export const createDomainGpsCredential = (
  domainId: string,
  createGpsCredentialRequest: BodyType<CreateGpsCredentialRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdminGpsCredentialDto>(
    {
      url: `/api/admin/domains/${domainId}/gps-credentials`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createGpsCredentialRequest,
      signal,
    },
    options
  )
}

export const getCreateDomainGpsCredentialMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createDomainGpsCredential>>,
    TError,
    { domainId: string; data: BodyType<CreateGpsCredentialRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof createDomainGpsCredential>>,
  TError,
  { domainId: string; data: BodyType<CreateGpsCredentialRequest> },
  TContext
> => {
  const mutationKey = ['createDomainGpsCredential']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createDomainGpsCredential>>,
    { domainId: string; data: BodyType<CreateGpsCredentialRequest> }
  > = (props) => {
    const { domainId, data } = props ?? {}

    return createDomainGpsCredential(domainId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateDomainGpsCredentialMutationResult = NonNullable<
  Awaited<ReturnType<typeof createDomainGpsCredential>>
>
export type CreateDomainGpsCredentialMutationBody = BodyType<CreateGpsCredentialRequest>
export type CreateDomainGpsCredentialMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Create GPS credential
 */
export const useCreateDomainGpsCredential = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createDomainGpsCredential>>,
      TError,
      { domainId: string; data: BodyType<CreateGpsCredentialRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createDomainGpsCredential>>,
  TError,
  { domainId: string; data: BodyType<CreateGpsCredentialRequest> },
  TContext
> => {
  const mutationOptions = getCreateDomainGpsCredentialMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Update a GPS credential for a domain
 * @summary Update GPS credential
 */
export const updateDomainGpsCredential = (
  domainId: string,
  credentialId: string,
  updateGpsCredentialRequest: BodyType<UpdateGpsCredentialRequest>,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<AdminGpsCredentialDto>(
    {
      url: `/api/admin/domains/${domainId}/gps-credentials/${credentialId}`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: updateGpsCredentialRequest,
    },
    options
  )
}

export const getUpdateDomainGpsCredentialMutationOptions = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateDomainGpsCredential>>,
    TError,
    { domainId: string; credentialId: string; data: BodyType<UpdateGpsCredentialRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateDomainGpsCredential>>,
  TError,
  { domainId: string; credentialId: string; data: BodyType<UpdateGpsCredentialRequest> },
  TContext
> => {
  const mutationKey = ['updateDomainGpsCredential']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateDomainGpsCredential>>,
    { domainId: string; credentialId: string; data: BodyType<UpdateGpsCredentialRequest> }
  > = (props) => {
    const { domainId, credentialId, data } = props ?? {}

    return updateDomainGpsCredential(domainId, credentialId, data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UpdateDomainGpsCredentialMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateDomainGpsCredential>>
>
export type UpdateDomainGpsCredentialMutationBody = BodyType<UpdateGpsCredentialRequest>
export type UpdateDomainGpsCredentialMutationError = ErrorType<ErrorResponse | void>

/**
 * @summary Update GPS credential
 */
export const useUpdateDomainGpsCredential = <
  TError = ErrorType<ErrorResponse | void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateDomainGpsCredential>>,
      TError,
      { domainId: string; credentialId: string; data: BodyType<UpdateGpsCredentialRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateDomainGpsCredential>>,
  TError,
  { domainId: string; credentialId: string; data: BodyType<UpdateGpsCredentialRequest> },
  TContext
> => {
  const mutationOptions = getUpdateDomainGpsCredentialMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Delete a GPS credential for a domain
 * @summary Delete GPS credential
 */
export const deleteDomainGpsCredential = (
  domainId: string,
  credentialId: string,
  options?: SecondParameter<typeof axiosMutator>
) => {
  return axiosMutator<void>(
    { url: `/api/admin/domains/${domainId}/gps-credentials/${credentialId}`, method: 'DELETE' },
    options
  )
}

export const getDeleteDomainGpsCredentialMutationOptions = <
  TError = ErrorType<void | ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDomainGpsCredential>>,
    TError,
    { domainId: string; credentialId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDomainGpsCredential>>,
  TError,
  { domainId: string; credentialId: string },
  TContext
> => {
  const mutationKey = ['deleteDomainGpsCredential']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDomainGpsCredential>>,
    { domainId: string; credentialId: string }
  > = (props) => {
    const { domainId, credentialId } = props ?? {}

    return deleteDomainGpsCredential(domainId, credentialId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeleteDomainGpsCredentialMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDomainGpsCredential>>
>

export type DeleteDomainGpsCredentialMutationError = ErrorType<void | ErrorResponse>

/**
 * @summary Delete GPS credential
 */
export const useDeleteDomainGpsCredential = <
  TError = ErrorType<void | ErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDomainGpsCredential>>,
      TError,
      { domainId: string; credentialId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDomainGpsCredential>>,
  TError,
  { domainId: string; credentialId: string },
  TContext
> => {
  const mutationOptions = getDeleteDomainGpsCredentialMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Enable or disable a domain
 * @summary Toggle domain active status
 */
export const toggleDomainActive = (
  domainId: string,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<AdminDomainDto>(
    { url: `/api/admin/domains/${domainId}/toggle-active`, method: 'POST', signal },
    options
  )
}

export const getToggleDomainActiveMutationOptions = <
  TError = ErrorType<void | ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof toggleDomainActive>>,
    TError,
    { domainId: string },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof toggleDomainActive>>,
  TError,
  { domainId: string },
  TContext
> => {
  const mutationKey = ['toggleDomainActive']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof toggleDomainActive>>,
    { domainId: string }
  > = (props) => {
    const { domainId } = props ?? {}

    return toggleDomainActive(domainId, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ToggleDomainActiveMutationResult = NonNullable<
  Awaited<ReturnType<typeof toggleDomainActive>>
>

export type ToggleDomainActiveMutationError = ErrorType<void | ErrorResponse>

/**
 * @summary Toggle domain active status
 */
export const useToggleDomainActive = <TError = ErrorType<void | ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof toggleDomainActive>>,
      TError,
      { domainId: string },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof toggleDomainActive>>,
  TError,
  { domainId: string },
  TContext
> => {
  const mutationOptions = getToggleDomainActiveMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
