#!/usr/bin/env node
// Generator for UI routes.
// Source: contracts/routes.yaml
// Outputs:
//   frontend/src/config/paths.generated.ts
//   mobile/lib/config/paths.generated.dart
//   frontend/public/.well-known/apple-app-site-association
//   mobile/android/app/src/main/AndroidManifest.xml (between deeplink markers)

import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..')
const frontendReq = createRequire(path.join(repoRoot, 'frontend', 'package.json'))
const YAML = frontendReq('yaml')

const LOCALES = ['en', 'fr']
const DEFAULT_LOCALE = 'en'
const IOS_APP_ID = '7Q49262697.fr.pedalons.mobile'
const MARKER_BEGIN = '<!-- BEGIN generated-deeplinks -->'
const MARKER_END = '<!-- END generated-deeplinks -->'

const outputs = {
  yaml: path.join(repoRoot, 'contracts', 'routes.yaml'),
  pathsTs: path.join(repoRoot, 'frontend', 'src', 'config', 'paths.generated.ts'),
  pathsDart: path.join(repoRoot, 'mobile', 'lib', 'config', 'paths.generated.dart'),
  aasa: path.join(repoRoot, 'frontend', 'public', '.well-known', 'apple-app-site-association'),
  manifest: path.join(repoRoot, 'mobile', 'android', 'app', 'src', 'main', 'AndroidManifest.xml'),
}

function normalizeLocaleMap(value) {
  if (value === undefined || value === null) return null
  if (typeof value === 'string') return { [DEFAULT_LOCALE]: value }
  return value
}

function normalizeParams(params) {
  if (!params) return []
  return params.map((p) => ({ name: String(p) }))
}

function loadRoutes() {
  const raw = YAML.parse(readFileSync(outputs.yaml, 'utf8'))
  if (!raw || !Array.isArray(raw.routes)) {
    throw new Error('contracts/routes.yaml must define a top-level `routes:` array')
  }
  return raw.routes.map((route) => {
    const normalized = {
      id: route.id,
      path: normalizeLocaleMap(route.path),
      params: normalizeParams(route.params),
      web: route.web !== false,
      mobile: route.mobile === true,
      mobileName: route.mobileName ?? route.id,
      deeplink: route.deeplink === true,
    }
    if (!normalized.id) throw new Error(`route is missing id: ${JSON.stringify(route)}`)
    if (!normalized.path?.[DEFAULT_LOCALE]) {
      throw new Error(`route ${normalized.id} is missing path.${DEFAULT_LOCALE}`)
    }
    for (const locale of Object.keys(normalized.path)) {
      if (!LOCALES.includes(locale)) {
        throw new Error(
          `route ${normalized.id}: unknown locale "${locale}" — allowed: ${LOCALES.join(', ')}`
        )
      }
      for (const param of normalized.params) {
        if (!normalized.path[locale].includes(`{${param.name}}`)) {
          throw new Error(`route ${normalized.id}: param ${param.name} not found in ${locale} path`)
        }
      }
    }
    return normalized
  })
}

function paramSlotTs(name) {
  return `\${${name}}`
}

function paramSlotDart(name) {
  return `\$${name}`
}

function fillTemplate(template, params, slotFn) {
  let out = template
  for (const p of params) {
    out = out.split(`{${p.name}}`).join(slotFn(p.name))
  }
  return out
}

function tsParamSig(params) {
  return params.map((p) => `${p.name}: string`).join(', ')
}

function dartParamSig(params) {
  return params.map((p) => `String ${p.name}`).join(', ')
}

function localePathMap(route) {
  const base = route.path
  const result = {}
  for (const locale of LOCALES) {
    result[locale] = base[locale] ?? base[DEFAULT_LOCALE]
  }
  return result
}

function generatePathsTs(routes) {
  const lines = [
    '// GENERATED by scripts/generate-routes.mjs — edit contracts/routes.yaml instead.',
    '',
    "import { getCurrentLocale } from './locale-context'",
    '',
    `export type Locale = ${LOCALES.map((l) => `'${l}'`).join(' | ')}`,
    `export const LOCALES = [${LOCALES.map((l) => `'${l}'`).join(', ')}] as const satisfies readonly Locale[]`,
    `export const DEFAULT_LOCALE: Locale = '${DEFAULT_LOCALE}'`,
    '',
    '/** Type-safe path builders — returns URL in the current locale. */',
    'export const paths = {',
  ]
  for (const route of routes) {
    if (!route.web) continue
    const sig = tsParamSig(route.params)
    const map = localePathMap(route)
    const uniqueLocales = new Set(Object.values(map))
    if (uniqueLocales.size === 1) {
      const template = map[DEFAULT_LOCALE]
      const body =
        route.params.length === 0
          ? `'${template}'`
          : `\`${fillTemplate(template, route.params, paramSlotTs)}\``
      lines.push(`  ${route.id}: (${sig}) => ${body},`)
    } else {
      lines.push(`  ${route.id}: (${sig}) => {`)
      lines.push(`    switch (getCurrentLocale()) {`)
      for (const locale of LOCALES) {
        if (locale === DEFAULT_LOCALE) continue
        const template = map[locale]
        const body =
          route.params.length === 0
            ? `'${template}'`
            : `\`${fillTemplate(template, route.params, paramSlotTs)}\``
        lines.push(`      case '${locale}': return ${body}`)
      }
      const enTemplate = map[DEFAULT_LOCALE]
      const enBody =
        route.params.length === 0
          ? `'${enTemplate}'`
          : `\`${fillTemplate(enTemplate, route.params, paramSlotTs)}\``
      lines.push(`      default: return ${enBody}`)
      lines.push('    }')
      lines.push('  },')
    }
  }
  lines.push('} as const')
  lines.push('')
  lines.push('/** Per-locale URL variants — returns all locale pattern strings. */')
  lines.push('export const pathVariants = {')
  for (const route of routes) {
    if (!route.web) continue
    const sig = tsParamSig(route.params)
    const map = localePathMap(route)
    const entries = LOCALES.map((locale) => {
      const template = map[locale]
      const body =
        route.params.length === 0
          ? `'${template}'`
          : `\`${fillTemplate(template, route.params, paramSlotTs)}\``
      return `${locale}: ${body}`
    })
    lines.push(`  ${route.id}: (${sig}): Record<Locale, string> => ({ ${entries.join(', ')} }),`)
  }
  lines.push('} as const')
  lines.push('')
  return lines.join('\n')
}

function generatePathsDart(routes) {
  const lines = [
    '// GENERATED by scripts/generate-routes.mjs — edit contracts/routes.yaml instead.',
    '// ignore_for_file: lines_longer_than_80_chars',
    '',
    "import 'locale_context.dart';",
    '',
    '/// Type-safe path builders — returns URL in the current locale.',
    'class Paths {',
    '  Paths._();',
    '',
  ]
  for (const route of routes) {
    if (!route.mobile) continue
    const sig = dartParamSig(route.params)
    const map = localePathMap(route)
    const uniqueLocales = new Set(Object.values(map))
    if (uniqueLocales.size === 1) {
      const template = map[DEFAULT_LOCALE]
      const body =
        route.params.length === 0
          ? `'${template}'`
          : `'${fillTemplate(template, route.params, paramSlotDart)}'`
      lines.push(`  static String ${route.mobileName}(${sig}) => ${body};`)
    } else {
      lines.push(`  static String ${route.mobileName}(${sig}) {`)
      lines.push('    switch (getCurrentLocale()) {')
      for (const locale of LOCALES) {
        if (locale === DEFAULT_LOCALE) continue
        const template = map[locale]
        const body =
          route.params.length === 0
            ? `'${template}'`
            : `'${fillTemplate(template, route.params, paramSlotDart)}'`
        lines.push(`      case '${locale}':`)
        lines.push(`        return ${body};`)
      }
      const enTemplate = map[DEFAULT_LOCALE]
      const enBody =
        route.params.length === 0
          ? `'${enTemplate}'`
          : `'${fillTemplate(enTemplate, route.params, paramSlotDart)}'`
      lines.push('      default:')
      lines.push(`        return ${enBody};`)
      lines.push('    }')
      lines.push('  }')
    }
  }
  lines.push('}')
  lines.push('')
  lines.push('/// Per-locale URL variants — returns all locale pattern strings.')
  lines.push('class PathVariants {')
  lines.push('  PathVariants._();')
  lines.push('')
  for (const route of routes) {
    if (!route.mobile) continue
    const sig = dartParamSig(route.params)
    const map = localePathMap(route)
    const entries = LOCALES.map((locale) => {
      const template = map[locale]
      const body =
        route.params.length === 0
          ? `'${template}'`
          : `'${fillTemplate(template, route.params, paramSlotDart)}'`
      return `'${locale}': ${body}`
    })
    lines.push(
      `  static Map<String, String> ${route.mobileName}(${sig}) => {${entries.join(', ')}};`
    )
  }
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function aasaPatterns(routes) {
  const seen = new Set()
  const patterns = []
  for (const route of routes) {
    if (!route.deeplink) continue
    const map = localePathMap(route)
    for (const locale of LOCALES) {
      let pattern = map[locale]
      for (const p of route.params) {
        pattern = pattern.split(`{${p.name}}`).join('*')
      }
      if (!seen.has(pattern)) {
        seen.add(pattern)
        patterns.push(pattern)
      }
    }
  }
  return patterns
}

function generateAasa(routes) {
  const payload = {
    applinks: {
      apps: [],
      details: [
        {
          appID: IOS_APP_ID,
          paths: aasaPatterns(routes),
        },
      ],
    },
    webcredentials: {
      apps: [IOS_APP_ID],
    },
  }
  return JSON.stringify(payload, null, 2) + '\n'
}

function manifestEntries(routes) {
  const seen = new Set()
  const entries = []
  for (const route of routes) {
    if (!route.deeplink) continue
    const map = localePathMap(route)
    for (const locale of LOCALES) {
      const template = map[locale]
      let attr, value
      if (route.params.length === 0) {
        attr = 'android:path'
        value = template
      } else {
        attr = 'android:pathPattern'
        value = route.params.reduce((acc, p) => acc.split(`{${p.name}}`).join('.*'), template)
      }
      const key = `${attr}:${value}`
      if (!seen.has(key)) {
        seen.add(key)
        entries.push({ attr, value })
      }
    }
  }
  return entries
}

function generateManifestBlock(routes, indent) {
  return manifestEntries(routes)
    .map((e) => `${indent}<data ${e.attr}="${e.value}" />`)
    .join('\n')
}

function injectIntoManifest(routes) {
  const content = readFileSync(outputs.manifest, 'utf8')
  const beginIdx = content.indexOf(MARKER_BEGIN)
  const endIdx = content.indexOf(MARKER_END)
  if (beginIdx === -1 || endIdx === -1) {
    throw new Error(
      `AndroidManifest.xml is missing deeplink markers (${MARKER_BEGIN} / ${MARKER_END})`
    )
  }
  const lineStart = content.lastIndexOf('\n', beginIdx) + 1
  const indent = content.slice(lineStart, beginIdx)
  const block = generateManifestBlock(routes, indent)
  const before = content.slice(0, beginIdx + MARKER_BEGIN.length)
  const after = content.slice(endIdx)
  return `${before}\n${block}\n${indent}${after}`
}

function writeIfChanged(target, content) {
  let prev = null
  try {
    prev = readFileSync(target, 'utf8')
  } catch {}
  if (prev === content) return false
  writeFileSync(target, content)
  return true
}

function main() {
  const routes = loadRoutes()
  const seen = new Set()
  for (const r of routes) {
    if (seen.has(r.id)) throw new Error(`Duplicate route id: ${r.id}`)
    seen.add(r.id)
  }

  const results = [
    ['paths.generated.ts', outputs.pathsTs, generatePathsTs(routes)],
    ['paths.generated.dart', outputs.pathsDart, generatePathsDart(routes)],
    ['apple-app-site-association', outputs.aasa, generateAasa(routes)],
    ['AndroidManifest.xml', outputs.manifest, injectIntoManifest(routes)],
  ]

  let changed = 0
  for (const [, target, content] of results) {
    const didWrite = writeIfChanged(target, content)
    const rel = path.relative(repoRoot, target)
    console.log(`${didWrite ? 'wrote ' : 'skip  '} ${rel}${didWrite ? '' : ' (unchanged)'}`)
    if (didWrite) changed += 1
  }
  console.log(`Generated ${routes.length} routes; ${changed} file(s) updated.`)
}

main()
