/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Pedalons API
 * API for Pedalons Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get frontend configuration including auth and app settings
 * @summary Get application configuration
 */
export const GetConfigResponse = zod
  .object({
    webAuthnRpId: zod.string().describe('WebAuthn Relying Party ID (domain)'),
    appName: zod.string().describe('Application name'),
    singleTeam: zod.boolean().describe('Single team mode - team creation disabled'),
  })
  .describe('Application configuration')
