/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod'

/**
 * Get paginated list of ride templates for a team
 * @summary List ride templates
 */
export const ListTemplatesParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

export const listTemplatesQueryPageDefault = 0
export const listTemplatesQuerySizeDefault = 20

export const ListTemplatesQueryParams = zod.object({
  page: zod.number().default(listTemplatesQueryPageDefault).describe('Page number'),
  search: zod.string().optional().describe('Search by name'),
  size: zod.number().default(listTemplatesQuerySizeDefault).describe('Page size'),
})

export const ListTemplatesResponse = zod
  .object({
    templates: zod
      .array(
        zod
          .object({
            team: zod
              .object({
                id: zod.string().describe('Team ID (TSID)'),
                name: zod.string().describe('Team name'),
                slug: zod.string().describe('Team URL slug'),
                visibility: zod.enum(['TEAM', 'PUBLIC']),
              })
              .describe('Team information'),
            id: zod.string().describe('Template ID (TSID)'),
            slug: zod.string().describe('Template slug'),
            name: zod.string().describe('Template name'),
            markdown: zod.string().describe('Template description (markdown)'),
            visibility: zod.enum(['TEAM', 'PUBLIC']),
            status: zod.enum(['DRAFT', 'PUBLISHED', 'CANCELLED']),
            createdAt: zod.iso.datetime({}),
            updatedAt: zod.iso.datetime({}),
            groupCount: zod.number().describe('Number of groups'),
            groups: zod
              .array(
                zod
                  .object({
                    id: zod.string().describe('Group ID (TSID)'),
                    name: zod.string().describe('Group name'),
                    time: zod.string().optional(),
                    averageSpeed: zod.number().optional().describe('Average speed in km\/h'),
                    maxParticipants: zod.number().optional().describe('Maximum participants'),
                    sortOrder: zod.number().describe('Sort order'),
                  })
                  .describe('Ride template group information')
              )
              .describe('Template groups'),
          })
          .describe('Ride template response')
      )
      .describe('List of templates'),
    total: zod.number().describe('Total number of templates'),
    page: zod.number().describe('Current page number'),
    size: zod.number().describe('Page size'),
  })
  .describe('Paginated ride template list response')

/**
 * Create a new ride template. Requires organizer permissions.
 * @summary Create ride template
 */
export const CreateTemplateParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
})

export const createTemplateBodyNameMax = 200

export const createTemplateBodyNameRegExp = new RegExp('\\S')
export const createTemplateBodyGroupsItemNameMax = 200

export const createTemplateBodyGroupsItemNameRegExp = new RegExp('\\S')

export const CreateTemplateBody = zod
  .object({
    name: zod
      .string()
      .min(1)
      .max(createTemplateBodyNameMax)
      .regex(createTemplateBodyNameRegExp)
      .describe('Template name'),
    markdown: zod.string().describe('Template description (markdown)'),
    visibility: zod.enum(['TEAM', 'PUBLIC']),
    status: zod.enum(['DRAFT', 'PUBLISHED', 'CANCELLED']),
    groups: zod
      .array(
        zod
          .object({
            id: zod.string().optional().describe('Group ID (TSID) - only for updates'),
            name: zod
              .string()
              .min(1)
              .max(createTemplateBodyGroupsItemNameMax)
              .regex(createTemplateBodyGroupsItemNameRegExp)
              .describe('Group name'),
            time: zod.string().optional(),
            averageSpeed: zod.number().optional().describe('Average speed in km\/h'),
            maxParticipants: zod.number().optional().describe('Maximum participants'),
          })
          .describe('Ride template group request')
      )
      .describe('Template groups'),
  })
  .describe('Ride template request')

/**
 * Update ride template information. Requires organizer permissions.
 * @summary Update ride template
 */
export const UpdateTemplateParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
  templateSlug: zod.string().describe('Template URL slug'),
})

export const updateTemplateBodyNameMax = 200

export const updateTemplateBodyNameRegExp = new RegExp('\\S')
export const updateTemplateBodyGroupsItemNameMax = 200

export const updateTemplateBodyGroupsItemNameRegExp = new RegExp('\\S')

export const UpdateTemplateBody = zod
  .object({
    name: zod
      .string()
      .min(1)
      .max(updateTemplateBodyNameMax)
      .regex(updateTemplateBodyNameRegExp)
      .describe('Template name'),
    markdown: zod.string().describe('Template description (markdown)'),
    visibility: zod.enum(['TEAM', 'PUBLIC']),
    status: zod.enum(['DRAFT', 'PUBLISHED', 'CANCELLED']),
    groups: zod
      .array(
        zod
          .object({
            id: zod.string().optional().describe('Group ID (TSID) - only for updates'),
            name: zod
              .string()
              .min(1)
              .max(updateTemplateBodyGroupsItemNameMax)
              .regex(updateTemplateBodyGroupsItemNameRegExp)
              .describe('Group name'),
            time: zod.string().optional(),
            averageSpeed: zod.number().optional().describe('Average speed in km\/h'),
            maxParticipants: zod.number().optional().describe('Maximum participants'),
          })
          .describe('Ride template group request')
      )
      .describe('Template groups'),
  })
  .describe('Ride template request')

export const UpdateTemplateResponse = zod
  .object({
    team: zod
      .object({
        id: zod.string().describe('Team ID (TSID)'),
        name: zod.string().describe('Team name'),
        slug: zod.string().describe('Team URL slug'),
        visibility: zod.enum(['TEAM', 'PUBLIC']),
      })
      .describe('Team information'),
    id: zod.string().describe('Template ID (TSID)'),
    slug: zod.string().describe('Template slug'),
    name: zod.string().describe('Template name'),
    markdown: zod.string().describe('Template description (markdown)'),
    visibility: zod.enum(['TEAM', 'PUBLIC']),
    status: zod.enum(['DRAFT', 'PUBLISHED', 'CANCELLED']),
    createdAt: zod.iso.datetime({}),
    updatedAt: zod.iso.datetime({}),
    groupCount: zod.number().describe('Number of groups'),
    groups: zod
      .array(
        zod
          .object({
            id: zod.string().describe('Group ID (TSID)'),
            name: zod.string().describe('Group name'),
            time: zod.string().optional(),
            averageSpeed: zod.number().optional().describe('Average speed in km\/h'),
            maxParticipants: zod.number().optional().describe('Maximum participants'),
            sortOrder: zod.number().describe('Sort order'),
          })
          .describe('Ride template group information')
      )
      .describe('Template groups'),
  })
  .describe('Ride template response')

/**
 * Get detailed ride template information
 * @summary Get ride template
 */
export const GetTemplateParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
  templateSlug: zod.string().describe('Template URL slug'),
})

export const GetTemplateResponse = zod
  .object({
    team: zod
      .object({
        id: zod.string().describe('Team ID (TSID)'),
        name: zod.string().describe('Team name'),
        slug: zod.string().describe('Team URL slug'),
        visibility: zod.enum(['TEAM', 'PUBLIC']),
      })
      .describe('Team information'),
    id: zod.string().describe('Template ID (TSID)'),
    slug: zod.string().describe('Template slug'),
    name: zod.string().describe('Template name'),
    markdown: zod.string().describe('Template description (markdown)'),
    visibility: zod.enum(['TEAM', 'PUBLIC']),
    status: zod.enum(['DRAFT', 'PUBLISHED', 'CANCELLED']),
    createdAt: zod.iso.datetime({}),
    updatedAt: zod.iso.datetime({}),
    groupCount: zod.number().describe('Number of groups'),
    groups: zod
      .array(
        zod
          .object({
            id: zod.string().describe('Group ID (TSID)'),
            name: zod.string().describe('Group name'),
            time: zod.string().optional(),
            averageSpeed: zod.number().optional().describe('Average speed in km\/h'),
            maxParticipants: zod.number().optional().describe('Maximum participants'),
            sortOrder: zod.number().describe('Sort order'),
          })
          .describe('Ride template group information')
      )
      .describe('Template groups'),
  })
  .describe('Ride template response')

/**
 * Soft delete a ride template. Requires organizer permissions.
 * @summary Delete ride template
 */
export const DeleteTemplateParams = zod.object({
  teamSlug: zod.string().describe('Team URL slug'),
  templateSlug: zod.string().describe('Template URL slug'),
})
