package fr.pedalons.service.notification;

import fr.pedalons.repository.notification.NotificationDeliveryRepository;
import fr.pedalons.repository.notification.NotificationEventRepository;
import fr.pedalons.repository.notification.NotificationRepository;
import fr.pedalons.repository.notification.TeamWebhookDeliveryRepository;
import io.quarkus.narayana.jta.QuarkusTransaction;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import org.eclipse.microprofile.config.inject.ConfigProperty;

/**
 * Drops events past the retention window, with their notifications and deliveries.
 *
 * <p>Children are deleted explicitly rather than left to the {@code on delete cascade} of the
 * migration: the test schema is generated by Hibernate, which knows nothing of it. One short
 * transaction per slice, so a large first purge never holds locks on the inbox for long.
 */
@ApplicationScoped
public class NotificationRetentionService {

  private static final int SLICE = 500;

  @Inject NotificationEventRepository eventRepository;
  @Inject NotificationRepository notificationRepository;
  @Inject NotificationDeliveryRepository deliveryRepository;
  @Inject TeamWebhookDeliveryRepository webhookDeliveryRepository;

  @ConfigProperty(name = "pedalons.notifications.retention-days", defaultValue = "90")
  int retentionDays;

  /** Returns how many events were deleted. */
  public int purgeExpired() {
    Instant cutoff = Instant.now().minus(retentionDays, ChronoUnit.DAYS);
    int total = 0;
    while (true) {
      int deleted =
          QuarkusTransaction.requiringNew()
              .call(
                  () -> {
                    List<Long> ids = eventRepository.findIdsCreatedBefore(cutoff, SLICE);
                    if (ids.isEmpty()) {
                      return 0;
                    }
                    deliveryRepository.deleteByEventIds(ids);
                    webhookDeliveryRepository.deleteByEventIds(ids);
                    notificationRepository.deleteByEventIds(ids);
                    eventRepository.delete("id in ?1", ids);
                    return ids.size();
                  });
      total += deleted;
      if (deleted < SLICE) {
        return total;
      }
    }
  }
}
