package com.tribly.dto.error;

public enum ErrorCode {
  BAD_REQUEST,
  NOT_FOUND,
  UNAUTHORIZED,
  FORBIDDEN,
  INTERNAL_ERROR,
  UNKNOWN,
  VALIDATION,
  BUSINESS_RULE,
  LAST_ADMIN,
  ALREADY_REGISTERED,
  NOT_REGISTERED,
  INVALID_SLUG,
  SLUG_TAKEN,
  USER_NOT_SYNCED,
  GROUP_FULL,
  INVALID_VISIBILITY,
  PUBLIC_TRIP_PRIVATE_ROUTE,
  GPX_FAILURE,
  FILE_REQUIRED,
  TOO_MANY_TEAM_PAGES,
  GPX_EMPTY,
  INVALID_FORMAT,
  RENTAL_PERIOD_MISSING,
  STATUS_INVALID,
  PUBLIC_RIDE_PRIVATE_ROUTE
}
