/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * Tribly API
 * API for Tribly Cycling Team Management Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'

import type {
  CompleteRequest,
  DeviceRequest,
  ErrorResponse,
  KarooDeviceCodeResponse,
  KarooTokenRequest,
  KarooTokenResponse,
  VerifyParams,
  VerifyResponse,
} from '../../dto'

import { axiosMutator } from '../../../lib/axiosInstance'
import type { ErrorType, BodyType } from '../../../lib/axiosInstance'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * Called by frontend after user authenticates via OTP
 * @summary Complete device authorization
 */
export const karooComplete = (
  completeRequest: BodyType<CompleteRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<unknown>(
    {
      url: `/api/karoo/oauth/complete`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: completeRequest,
      signal,
    },
    options
  )
}

export const getKarooCompleteMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof karooComplete>>,
    TError,
    { data: BodyType<CompleteRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof karooComplete>>,
  TError,
  { data: BodyType<CompleteRequest> },
  TContext
> => {
  const mutationKey = ['karooComplete']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof karooComplete>>,
    { data: BodyType<CompleteRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return karooComplete(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type KarooCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof karooComplete>>>
export type KarooCompleteMutationBody = BodyType<CompleteRequest>
export type KarooCompleteMutationError = ErrorType<ErrorResponse>

/**
 * @summary Complete device authorization
 */
export const useKarooComplete = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof karooComplete>>,
      TError,
      { data: BodyType<CompleteRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof karooComplete>>,
  TError,
  { data: BodyType<CompleteRequest> },
  TContext
> => {
  const mutationOptions = getKarooCompleteMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Start device code flow - returns user code and verification URL
 * @summary Request device code
 */
export const device = (
  deviceRequest: BodyType<DeviceRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<KarooDeviceCodeResponse>(
    {
      url: `/api/karoo/oauth/device`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: deviceRequest,
      signal,
    },
    options
  )
}

export const getDeviceMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof device>>,
    TError,
    { data: BodyType<DeviceRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof device>>,
  TError,
  { data: BodyType<DeviceRequest> },
  TContext
> => {
  const mutationKey = ['device']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof device>>,
    { data: BodyType<DeviceRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return device(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type DeviceMutationResult = NonNullable<Awaited<ReturnType<typeof device>>>
export type DeviceMutationBody = BodyType<DeviceRequest>
export type DeviceMutationError = ErrorType<ErrorResponse>

/**
 * @summary Request device code
 */
export const useDevice = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof device>>,
      TError,
      { data: BodyType<DeviceRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof device>>,
  TError,
  { data: BodyType<DeviceRequest> },
  TContext
> => {
  const mutationOptions = getDeviceMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Exchange device code or refresh token for access tokens. Returns 'authorization_pending' error while waiting for user.
 * @summary Exchange code for tokens
 */
export const karooToken = (
  karooTokenRequest: BodyType<KarooTokenRequest>,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<KarooTokenResponse>(
    {
      url: `/api/karoo/oauth/token`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: karooTokenRequest,
      signal,
    },
    options
  )
}

export const getKarooTokenMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof karooToken>>,
    TError,
    { data: BodyType<KarooTokenRequest> },
    TContext
  >
  request?: SecondParameter<typeof axiosMutator>
}): UseMutationOptions<
  Awaited<ReturnType<typeof karooToken>>,
  TError,
  { data: BodyType<KarooTokenRequest> },
  TContext
> => {
  const mutationKey = ['karooToken']
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined }

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof karooToken>>,
    { data: BodyType<KarooTokenRequest> }
  > = (props) => {
    const { data } = props ?? {}

    return karooToken(data, requestOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type KarooTokenMutationResult = NonNullable<Awaited<ReturnType<typeof karooToken>>>
export type KarooTokenMutationBody = BodyType<KarooTokenRequest>
export type KarooTokenMutationError = ErrorType<ErrorResponse>

/**
 * @summary Exchange code for tokens
 */
export const useKarooToken = <TError = ErrorType<ErrorResponse>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof karooToken>>,
      TError,
      { data: BodyType<KarooTokenRequest> },
      TContext
    >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof karooToken>>,
  TError,
  { data: BodyType<KarooTokenRequest> },
  TContext
> => {
  const mutationOptions = getKarooTokenMutationOptions(options)

  return useMutation(mutationOptions, queryClient)
}
/**
 * Frontend uses this to verify user code before showing auth flow
 * @summary Check user code validity
 */
export const verify = (
  params?: VerifyParams,
  options?: SecondParameter<typeof axiosMutator>,
  signal?: AbortSignal
) => {
  return axiosMutator<VerifyResponse>(
    { url: `/api/karoo/oauth/verify`, method: 'GET', params, signal },
    options
  )
}

export const getVerifyQueryKey = (params?: VerifyParams) => {
  return [`/api/karoo/oauth/verify`, ...(params ? [params] : [])] as const
}

export const getVerifyQueryOptions = <
  TData = Awaited<ReturnType<typeof verify>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: VerifyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof verify>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getVerifyQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof verify>>> = ({ signal }) =>
    verify(params, requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof verify>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type VerifyQueryResult = NonNullable<Awaited<ReturnType<typeof verify>>>
export type VerifyQueryError = ErrorType<ErrorResponse>

export function useVerify<
  TData = Awaited<ReturnType<typeof verify>>,
  TError = ErrorType<ErrorResponse>,
>(
  params: undefined | VerifyParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof verify>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof verify>>,
          TError,
          Awaited<ReturnType<typeof verify>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerify<
  TData = Awaited<ReturnType<typeof verify>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: VerifyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof verify>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof verify>>,
          TError,
          Awaited<ReturnType<typeof verify>>
        >,
        'initialData'
      >
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useVerify<
  TData = Awaited<ReturnType<typeof verify>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: VerifyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof verify>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Check user code validity
 */

export function useVerify<
  TData = Awaited<ReturnType<typeof verify>>,
  TError = ErrorType<ErrorResponse>,
>(
  params?: VerifyParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof verify>>, TError, TData>>
    request?: SecondParameter<typeof axiosMutator>
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVerifyQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = queryOptions.queryKey

  return query
}
